VnEduPlus/Controllers/GiaoVienChuNhiemVaLopHocController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lib.Web.Mvc.JQuery.JqGrid;
using VnEduPlus.CmonFunction;
using VnEduPlus.Models;
using System.Globalization;
using System.Threading;
namespace VnEduPlus.Controllers
{
    public class GiaoVienChuNhiemVaLopHocController : Controller
    {

        /// <summary>
        /// Khai bao bien toan cuc
        /// </summary>
        EDUNP_CAP1Entities db = new EDUNP_CAP1Entities();

        /// <summary>
        /// lay username dang nhap 
        /// </summary>
        /// <returns></returns>
        public string getUserName()
        {
            return User.Identity.Name.ToString() == "" ? "superadmin" : User.Identity.Name.ToString();

        }
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.Message = "Chương trình ứng dụng công nghệ thông tin quản lý trường học 2012-2020!";

            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize]

        #region Quản lý nhận xét

        public ActionResult TemplateNhanXetThang()
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Thongbao");

            }

            // lay thong tin truong 
            string userName = getUserName();
            int idTruong = Cmon.getIdtruong(userName, db);
            bool isHieuTruong = Cmon.isHieuTruong(idTruong, userName);
            ViewBag.isHieuTruong = isHieuTruong;
            string namHoc = Cmon.GetNamHienTai(idTruong); 
            ViewBag.namhoc = namHoc; 
            ViewBag.idtruong = idTruong;
            ViewBag.danhMucTieuChi = Cmon.createDanhMuc();
            ViewBag.danhMucThang = Cmon.createCacThangCoDinh(idTruong, db);
            ViewBag.tenuser = Cmon.GetnameUser(userName);
			DateTime d = DateTime.Now;
			string month = (d.Month < 9 && d.Month > 5) ? "09" : d.Month.ToString();

			ViewBag.thanght = month;
			//"01/" + month + "/" + d.Year.ToString();

            // Load lop hoc cua user


            var lopHoc = (from lophoc in db.LopHocs
                          let maLop = (from userLop in db.Users_LopHoc
                                      join userMon in db.Users_Monhoc
                                      on userLop.UserName equals userMon.UserName
                                      where userLop.idTruong == idTruong && userLop.NamHoc == namHoc && userLop.UserName == userName
                                          select userLop.MaLop).Distinct()
                         where maLop.Contains(lophoc.MaLop) && lophoc.idTruong == idTruong && lophoc.NamHoc== namHoc
                         select lophoc).ToList();

			string maLopMacDinh =  (lopHoc != null && lopHoc.Count > 0) ? lopHoc[0].MaLop.ToString() : "";
			ViewBag.maLopMacDinh = maLopMacDinh;

            LopHoc emptyLopHoc = new LopHoc();
            emptyLopHoc.MaLop = "-1";
            emptyLopHoc.TenLop = "--Chọn lớp học--";
            lopHoc.Insert(0, emptyLopHoc);
            ViewBag.lopHoc = lopHoc;
             

            return View();
        }

		[AcceptVerbs(HttpVerbs.Get)]
		[Authorize]

		#region Quản lý nhận xét định kì

		public ActionResult TemplateNhanXetDinhKy()
		{
			if (!Request.IsAuthenticated)
			{
				return RedirectToAction("Index", "Thongbao");

			}

			// lay thong tin truong 
			string userName = getUserName();
			int idTruong = Cmon.getIdtruong(userName, db);
			bool isHieuTruong = Cmon.isHieuTruong(idTruong, userName);
			ViewBag.isHieuTruong = isHieuTruong;
			string namHoc = Cmon.GetNamHienTai(idTruong);
			ViewBag.namhoc = namHoc;
			ViewBag.idtruong = idTruong;
			ViewBag.danhMucTieuChi = Cmon.createDanhMuc();
			ViewBag.danhMucThang = Cmon.createCacThangCoDinh(idTruong, db);
			ViewBag.tenuser = Cmon.GetnameUser(userName);

			ViewBag.hocKy = Cmon.CreateHocKyTheoDanhGia();

			// Load lop hoc cua user


			var lopHoc = (from lophoc in db.LopHocs
						  let maLop = (from userLop in db.Users_LopHoc
									   join userMon in db.Users_Monhoc
									   on userLop.UserName equals userMon.UserName
									   where userLop.idTruong == idTruong && userLop.NamHoc == namHoc && userLop.UserName == userName
									   select userLop.MaLop).Distinct()
						  where maLop.Contains(lophoc.MaLop) && lophoc.idTruong == idTruong && lophoc.NamHoc == namHoc
						  select lophoc).ToList();

			string maLopMacDinh = (lopHoc != null && lopHoc.Count > 0) ? lopHoc[0].MaLop.ToString() : "";
			ViewBag.maLopMacDinh = maLopMacDinh;

			LopHoc emptyLopHoc = new LopHoc();
			emptyLopHoc.MaLop = "-1";
			emptyLopHoc.TenLop = "--Chọn lớp học--";
			lopHoc.Insert(0, emptyLopHoc);
			ViewBag.lopHoc = lopHoc;


			return View();
		}
		#endregion


		#region Quản lý thêm mới nhận xét

		public ActionResult AddNhanXet()
        {
            return PartialView(@"~/Views/GiaoVienChuNhiem/AddNhanXet.cshtml");
        }

        [HttpGet]
        public JsonResult ThemMoiNhanXet(int type, string maNhanXet, string tenNhanXet, bool isdefault, string thang, int idtruong)
        {
            string mess = "";
            if (string.IsNullOrEmpty(maNhanXet.Trim()))
                mess = "Yêu cầu nhập mã nhận xét";
            else if (string.IsNullOrEmpty(tenNhanXet.Trim()))
                mess = "Yêu cầu nhập tên nhận xét";
            else
            {
                Cmon.UpdateStatusCNNX(type, Int16.Parse(thang), db);
                DM_NhanXetMau_GVCN kt = new DM_NhanXetMau_GVCN();
                kt.Thang = Convert.ToInt16(thang);

                kt.idTruong = idtruong;
                kt.LoaiNhanXet = (short)type;
                kt.TenNhanXet = tenNhanXet;
                kt.MaNhanXet = maNhanXet.Trim();
                kt.UserCreated = getUserName();
                kt.isDefault = isdefault;
                db.DM_NhanXetMau_GVCN.AddObject(kt);
                int rs = db.SaveChanges();
                if (rs > 0)
                    mess = "OK";
                else
                    mess = "Thêm mới tiêu chí không thành công!";
            }
            return Json(mess, JsonRequestBehavior.AllowGet);
        }


        #endregion

        #region Quản lý sửa nhận xét

        public ActionResult EditNhanXet(string loaiNhanXet, string manx, string thang, int idTruong)
        {

            short th = Convert.ToInt16(thang);
            short loaiNX = Convert.ToInt16(loaiNhanXet);
            var kthuc = (from kt in db.DM_NhanXetMau_GVCN.Where(t => t.LoaiNhanXet == loaiNX && t.Thang == th && t.MaNhanXet == manx && t.idTruong == idTruong) select kt).FirstOrDefault();

            return PartialView(@"~/Views/GiaoVienChuNhiem/EditNhanXet.cshtml", kthuc);
        }

        [HttpGet]
        public JsonResult UpdateNhanXet(int type, string maNhanXet, string tenNhanXet, bool isdefault, string thang, int idtruong)
        {
            string mess = "";
            if (string.IsNullOrEmpty(maNhanXet.Trim()))
                mess = "Yêu cầu nhập mã nhận xét";
            else if (string.IsNullOrEmpty(tenNhanXet.Trim()))
                mess = "Yêu cầu nhập tên nhận xét";
            else
            {
                Cmon.UpdateStatusCNNX(type, Int16.Parse(thang), db);
                short th = Convert.ToInt16(thang);
                DM_NhanXetMau_GVCN kt = (from kthuc in db.DM_NhanXetMau_GVCN.Where(t => t.LoaiNhanXet == type && t.MaNhanXet == maNhanXet && t.Thang == th && t.idTruong == idtruong) select kthuc).FirstOrDefault();
                if (kt != null)
                {
                    kt.MaNhanXet = maNhanXet.Trim();
                    kt.TenNhanXet = tenNhanXet;
                    kt.UserCreated = getUserName();
                    kt.isDefault = isdefault;
                    int rs = db.SaveChanges();
                    if (rs > 0)
                        mess = "OK";
                    else
                        mess = "Cập nhật nhận xét không thành công!";
                }
                else
                {
                    mess = "Không có thông tin cập nhật!";
                }
            }
            return Json(mess, JsonRequestBehavior.AllowGet);
        }


        #endregion

        #region Quản lý xóa nhận xét
        [HttpGet]
        public JsonResult DeleteNhanXet(int type, string maNhanXet, string thang, int idtruong)
        {
            string mess = "";
            short th = Convert.ToInt16(thang);
            DM_NhanXetMau_GVCN kt = (from kthuc in db.DM_NhanXetMau_GVCN.Where(t => t.MaNhanXet == maNhanXet && t.LoaiNhanXet == type && t.Thang == th && t.idTruong == idtruong) select kthuc).FirstOrDefault();
            if (kt != null)
            {

                db.DM_NhanXetMau_GVCN.DeleteObject(kt);
                int del = db.SaveChanges();
                if (del > 0)
                    mess = "OK";
                else
                    mess = "Xóa tiêu chí không thành công!";
            }
            else
            {
                mess = "Không có thông tin để xóa!";
            }
            return Json(mess, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Quản lý hiện thị danh sách nhận xét

        public List<HocSinhNhanXetNhom> getDanhSachHocSinh(int idTruong, int thang, string maLop, string namHoc)
        {
            List<HocSinhNhanXetNhom> danhSachHocSinh = new List<HocSinhNhanXetNhom>();
            switch (thang)
            {
                case 8:
                   danhSachHocSinh = (from hs in db.HocSinhs
                                       where hs.idTruong == idTruong && hs.MaLop == maLop && hs.NamHoc == namHoc && !(from hsqt in db.HocSinh_QuaTrinh.Where(hsqt => hsqt.idTruong == idTruong && hsqt.NamHoc == namHoc && hsqt.MaLop == maLop && hsqt.MaQuaTrinh == "BH")
                                                                                                                      select hsqt.MaHocSinh).Contains(hs.MaHocSinh)

VnEduPlus/Views/GiaoVienChuNhiemVaLopHoc/HienThiDanhSachNhanXet_04102015.cshtml
@model VnEduPlus.Models.MauCauNhanXet
@{
    ViewBag.Title = "Mâu câu Nhận xet tháng chủ nhiệm";
}
 
    <script type="text/javascript">
        $(document).ready(function () {
         // check all or remove check all checkboxk
      

       $("#isDefault").change(function(){
          $(".boxing").prop('checked', $(this).prop("checked"));
       });

         // xử lý quyền 

        if (@ViewBag.phanQuyen == 0) {
        
            $('#nhomNX').removeAttr("data-target");
            $('input[type="text"]').each(function() {
                $(this).prop('disabled', true);
            });

        } else {
          $('#nhomNX').attr("data-target");
        }


            // Khung chương trình
            $('#btnCT').click(function () {
                var idTruong = $('#idtruong').val();
                var maLop = $('#lopHoc').val();
                var maThang = $('#thang').val();
                $.ajax({
                    cache: true,
                    type: 'GET',
                    contentType: 'application/json; charset=utf-8',
                    url: '@Url.Action("HienThiKhungChuongTrinhGVCN", "KhungChuongTrinh")',
                    data: { idTruong: idTruong, maLop: maLop, maThang: maThang },
                    success: function (data) {
                        $('#content').html(data);
                    },

                    error: function (xhr, ajaxOptions, thrownError) {
                        alert('Failed to retrieve specification options.')
                    }


                });
            });

            //-------------------- check những học sinh đã có câu nhận xét-------

            $('.table-bordered input[type="text"]').on('keyup', function (evt) {
                var idcheckbox = this.id.substring(this.id, this.id.length - 2);
                var valueKT = $('#' + idcheckbox + "KT").val();
                var valueNL = $('#' + idcheckbox + "NL").val();
                var valuePC = $('#' + idcheckbox + "PC").val();
                $('#' + idcheckbox).prop('checked', true);
            });

            // get infomation of dialog 

            $('.modal-footer #chonnx').click(function () {
                // duyet qua tat ca cac checkbox 
                var mangCheckBox = [];
                var arr_noidung = ["", "", ""];

                // duyet qua tat ca checkbox duoc chon
                $('.boxing').each(function () {
                    if ($(this).prop('checked')) {
                        mangCheckBox.push(this.id);
                    }

                });

                $('#myModal').modal('toggle'); // mo dialog

                // lay gia tri nhan xet tu dialog box
                if ($('#DMKienThuc').val() != '-1') // có chọn câu nhận xét 
                {
                    var noidungKT = $('#DMKienThuc :selected').text();
                    arr_noidung[0] = (noidungKT);
                }

                if ($('#DMNangLuc').val() != '-1') // có chọn câu nhận xét 
                {
                    var noidungNL = $('#DMNangLuc :selected').text();
                    arr_noidung[1] = (noidungNL);
                }

                if ($('#DMPhamChat').val() != '-1') // có chọn câu nhận xét 
                {
                    var noidungPC = $('#DMPhamChat :selected').text();
                    arr_noidung[2] = (noidungPC);
                }

                //Do du lieu ra ngoai trang chinh
                debugger;
                $.each(mangCheckBox, function (id, value) {
                    if (arr_noidung[0] != '-1') {
                        $('#' + value + "KT").val(arr_noidung[0]); // xét value for kiến thức
                    }

                    // Năng lực
                    if (arr_noidung[1] != '-1') {
                        $('#' + value + "NL").val(arr_noidung[1]); // xét value for kiến thức
                    }

                    // Phẩm chất
                    if (arr_noidung[2] != '-1') {
                        $('#' + value + "PC").val(arr_noidung[2]); // xét value for kiến thức
                    }
                }); //end for

            });

            // xử lý nút lưu

            $('#luuNX').click(function () {
                var thang = $('#thang').val();
                var maLop = $('#lopHoc').val();
                var idTruong = $('#idtruong').val();
                // duyetj qua từng học sinh xem có giá trị nhận xét hay không rồi đem lưu xuống

                var listBoCauNhanXet = [];
                var mangCheckBox = [];
                // duyet qua tat ca checkbox duoc chon
                $('.boxing').each(function () {
                    if ($(this).prop('checked')) {
                        mangCheckBox.push(this.id);
                    }

                });

                debugger;
                // chỉ lấy những học sinh nào được check
                $.each(mangCheckBox, function (id, maHocSinh) {
                    var BoCauNhanXet = {};
                    var NoiDungNXKT = $('#' + maHocSinh + "KT").val();
                    var NoiDungNXNL = $('#' + maHocSinh + "NL").val();
                    var NoiDungNXPC = $('#' + maHocSinh + "PC").val();
                    var hoTenHS = $('#' + maHocSinh + "HT").text();
                    BoCauNhanXet.maHS = maHocSinh;
                    BoCauNhanXet.hoTen = hoTenHS;
                    BoCauNhanXet.kienThuc = NoiDungNXKT == "" ? "" : NoiDungNXKT;
                    BoCauNhanXet.nangLuc = NoiDungNXNL == "" ? "" : NoiDungNXNL;
                    BoCauNhanXet.phamChat = NoiDungNXPC == "" ? "" : NoiDungNXPC;
                    listBoCauNhanXet.push(BoCauNhanXet);

                });


                var dataWaper = {
                    idTruong: idTruong,
                    thang: thang,
                    maLop: maLop,
                    nhanXets: listBoCauNhanXet
                };    //convert to json


                debugger;
                // send to backend
                $.ajax({
                    cache: true,
                    type: 'POST',
                    contentType: 'application/json; charset=utf-8',
                    url: '@Url.Action("XuLyGanNhanXetNhomHocSinh", "GiaoVienChuNhiemVaLopHoc")',
                    data: JSON.stringify(dataWaper),
                    dataType: "json",
                    success: function (data) {
                        if (data && data == "OK") {
                            alert("Cập nhật nội dung nhận xét thành công!");

                        } else {
                            alert("Cập nhật nội dung nhận xét không thành công!");
                        }
                    },

                    error: function (xhr, ajaxOptions, thrownError) {
                        alert('Failed to retrieve specification options.')
                    }


                });

            });


        });                                               // end document.ready 
         

    </script>
     
 <div class="container" style="margin-top: 170px;"> 
  
 <button type="button" class="btn btn-primary bentrai">Tổng số : <span class="badge">@Model.hocSinhNhanXetNhom.Count</span> học sinh </button>
 <input type="button" id="btnCT" class="btn btn-primary benphai btn-sm" style="background-color:#0E5DA2; border-style:none" data-toggle="modal" data-target="#KhungCT" name="btnCT" value="Xem Khung Chương trình" />
  <table class="table table-bordered">
    <thead>
      <tr>
        <th style="width: 2%;">STT</th>
        <th style="width: 3%;"><input type="checkbox" name="isDefault" id="isDefault"  value="0" /></th>
        <th style="width: 15%;">Tên học sinh</th>
        <th style="width: 10%;">Ngày sinh</th>
        <th style="width: 23%;">NX Kiến thức</th>
        <th style="width: 23%;">NX Năng lực</th>
        <th style="width: 23%;">NX Phẩm chất</th>
      </tr>
    </thead>
    <tbody>
     @{
        
         for (int i = 0; i < Model.hocSinhNhanXetNhom.Count(); i++)
         {
             string STT = Model.hocSinhNhanXetNhom[i].STT.ToString();
             string maHocSinh = Model.hocSinhNhanXetNhom[i].maHocSinh;
             string tenHocSinh = Model.hocSinhNhanXetNhom[i].tenHocSinh;
             string idKT = maHocSinh + "KT";
             string idNL = maHocSinh + "NL";
             string idPC = maHocSinh + "PC";
             string idHoTen = maHocSinh + "HT";
             
            <tr>
            <td align="center">@STT</td>
            <td><input type="checkbox" name="isDefault" id="@maHocSinh" value="0" class="boxing" /></td>
            <td id="@idHoTen">@tenHocSinh</td>
            <td class="mahocsinh">@String.Format("{0:dd/MM/yyyy}", Model.hocSinhNhanXetNhom[i].ngaySinh)</td>
            <td><input type="text" id="@idKT" value ="@Model.hocSinhNhanXetNhom[i].nhanXetKienThuc"  class="contentNhanXet KienThuc" /></td>
            <td><input type="text" id="@idNL" value ="@Model.hocSinhNhanXetNhom[i].nhanXetNangLuc" class="contentNhanXet NangLuc"/></td>
            <td><input type="text" id="@idPC" value ="@Model.hocSinhNhanXetNhom[i].nhanXetPhamChat" class="contentNhanXet PhamChat" /></td>
            </tr>
         }
         
      }
      
    </tbody>
  </table>

  
 <!-- Modal -->
  <div id="TieuChiForm" style="display:none">
  </div>
 
</div> 
 

  <!-- Modal -->
  <div class="modal fade modalCenter" id="myModal" role="dialog">
    <div class="modal-dialog modalWidth">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Lựa chọn bộ câu hỏi</h4>
        </div>
        <div class="modal-body"> 
          <div class="row">
            <div class="col-sm-4" style="background-color:lavender;"><strong>Kiến thức</strong></div>
            <div class="col-sm-4" style="background-color:lavenderblush;"><stromg>Năng lực</stromg></div>
            <div class="col-sm-4" style="background-color:lavender;"><strong>Phẩm chất</strong></div>
          </div>

          <div class="row">
            <div class="col-sm-4" style="background-color:lavender;">@Html.DropDownListFor(x => Model.DMKienThuc, new SelectList(Model.DMKienThuc, "maNhanXet", "tenNhanXet"), new { @class = "textboxDialog" })</div>
            <div class="col-sm-4" style="background-color:lavenderblush;">@Html.DropDownListFor(x => Model.DMNangLuc, new SelectList(Model.DMNangLuc, "maNhanXet", "tenNhanXet"), new { @class = "textboxDialog" })</div>
            <div class="col-sm-4" style="background-color:lavender;">@Html.DropDownListFor(x => Model.DMPhamChat, new SelectList(Model.DMPhamChat, "maNhanXet", "tenNhanXet"), new { @class = "textboxDialog" })</div>
          </div>

        </div>

        <div class="modal-footer">
        <button type="button" class="btn btn-default" id="chonnx" data-dismiss="modal">Chọn nhận xét</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

  <!-- Modal khung chương trình -->
  <div class="modal fade modalCenter" id="KhungCT" role="dialog">
    <div class="modal-dialog modalWidth">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Khung chương trình của khối: @ViewBag.maKhoi</h4>
        </div>
        <div class="modal-body">         
          <div class="row"><div class="col-sm-12" style="background-color:lavender;" id="content"></div></div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

VnEduPlus/Views/GiaoVienChuNhiemVaLopHoc/NoiDungSoChuNhiem.cshtml
@model VnEduPlus.Models.MauCauNhanXet
@{
    ViewBag.Title = "Mâu câu Nhận xet tháng chủ nhiệm";
}
 
 <head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 <!-- import css bootstrap css and js ( bat buoc phai co)-->
 <link rel="stylesheet" href="@Url.Content("~/css/bootstrap/bootstrap.min.css")">
 <link href="@Url.Content("~/css/jquery.dataTables.css")" rel="stylesheet" type="text/css" />
 <script src="@Url.Content("~/js/bootstrap/js/bootstrap.min.js")"></script>
 <script src="@Url.Content("~/Scripts/jquery.dataTables.min.js")" type="text/javascript"></script>
</head>
    
 <div class="container"> 
  <input type="hidden" id="giaoVienCNGiangDay" value="@ViewBag.giaoVienChuNhiems" />
 @*<button type="button" class="btn btn-primary bentrai">Tổng số: <span class="badge">@Model.hocSinhNhanXetNhom.Count</span> học sinh </button>*@
  <table id="thongTinSoChuNhiem" class="table table-striped table-bordered" style="table-layout: fixed;" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th style="width: 4%; text-align: center;">STT</th>
        @*<th style="width: 3%;"><input type="checkbox" name="isDefault" id="isDefault" value="0" /></th>*@
        <th style="width: 17%; text-align: center;">Tên học sinh</th>
        <th style="width: 10%; text-align: center;">Ngày sinh</th>
        <th style="width: 23%; text-align: center;">NX Kiến thức</th>
        <th style="width: 23%; text-align: center;">NX Năng lực</th>
        <th style="width: 23%; text-align: center;">NX Phẩm chất</th>
      </tr>
    </thead>
    <tbody>
     @{ 
        
         for (int i = 0; i < Model.hocSinhNhanXetNhom.Count(); i++)
         {
             string maHocSinh = Model.hocSinhNhanXetNhom[i].maHocSinh;
             string tenHocSinh = Model.hocSinhNhanXetNhom[i].tenHocSinh;
             string idKT = maHocSinh + "KT";
             string idNL = maHocSinh + "NL";
             string idPC = maHocSinh + "PC";
             string idHoTen = maHocSinh + "HT";
             
            <tr>
            <td align="center">@(i + 1)</td>
            @*<td><input type="checkbox" name="isDefault" id="@maHocSinh" value="0" class="boxing" /></td>*@
            <td id="@idHoTen">@tenHocSinh</td>
            <td align="center" class="mahocsinh">@String.Format("{0:dd/MM/yyyy}", Model.hocSinhNhanXetNhom[i].ngaySinh)</td>
            <td style="word-wrap:break-word">@Model.hocSinhNhanXetNhom[i].nhanXetKienThuc</td>
            <td style="word-wrap:break-word">@Model.hocSinhNhanXetNhom[i].nhanXetNangLuc</td>
            <td style="word-wrap:break-word">@Model.hocSinhNhanXetNhom[i].nhanXetPhamChat</td>
            </tr>
         }
         
      }
      
    </tbody>
  </table>

  
  
</div> 
 
  
   