VnEduPlus/Models/TongHopDanhGia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VnEduPlus.Models
{
    public class TongHopDanhGia
    {
        public Khoi khoi { get; set; }
        public LopHocGiaoVien lophoc { get; set; }
        public HocKy hocky { get; set; }
        public HocSinhTongHop hocsinh { get; set; }
        public List<DanhMucMonHoc> dsMonHoc { get; set; }
    }

    public class HocSinhTongHop
    {
        public string MaHocSinh { get; set; }
        public string TenHocSinh { get; set; }
        public string MaLop { get; set; }
        public string TenLop { get; set; }

    }

    public class Khoi
    {
        public string MaKhoi { get; set; }
        public string TenKhoi { get; set; }
    }

    public class TapHocSinhDiem
    {
        public string HocSinh { get; set; }
        public string MaLop { get; set; }
        public string HocKy { get; set; }
    }

    public class ExcelBoMon
    {
        public string maLop { get; set; }
        public string thang { get; set; }
        public string maMonHoc { get; set; }
    }

    public class MonHocThi
    {
        public string maMon { get; set; }
        public bool thiHK { get; set; }
        public bool thiGHK { get; set; }
    }

    public class MonHocDanhGia
    {
        public string maMonHoc { get; set; }
        public string tenMonHoc { get; set; }
    }

    public class KetQuaMonDanhGia
    {
        public string maMonHoc { get; set; }
        public System.Data.DataTable dataTable { get; set; }
    }
}

VnEduPlus/Controllers/TongHopDanhGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lib.Web.Mvc.JQuery.JqGrid;
using VnEduPlus.CmonFunction;
using VnEduPlus.Models;
using System.Globalization;
using System.Threading;
using System.Data.SqlClient;
using System.Data;
using System.Configuration;
using System.IO;

namespace VnEduPlus.Controllers
{
    public class TongHopDanhGiaController : Controller
    {
        EDUNP_CAP1Entities db = new EDUNP_CAP1Entities();
        public string getUserName()
        {
            return User.Identity.Name.ToString() == "" ? "superadmin" : User.Identity.Name.ToString();

        }


        public ActionResult TongHopNhanXetHocSinh()
        {
            string userName = getUserName();

            int idTruong = Cmon.getIdtruong(userName, db);
            string namhoc = Cmon.GetNamHienTai(idTruong);
            bool isHieuTruong = Cmon.isHieuTruong(idTruong, userName);
            ViewBag.isHieuTruong = isHieuTruong;
            var khois = (from khoi in db.DM_Khoi
                         let makhoiList = from lh in db.LopHocs
                                          join userlh in db.Users_LopHoc
                                          on lh.MaLop equals userlh.MaLop
                                          where lh.idTruong == idTruong && lh.NamHoc == namhoc && userlh.UserName == userName
                                          select lh.MaKhoi
                         where makhoiList.Contains(khoi.MaKhoi) && khoi.idTruong == idTruong && khoi.NamHoc == namhoc
                         select khoi).ToList();

            DM_Khoi kl = new DM_Khoi();
            kl.MaKhoi = "";
            kl.TenKhoi = "--Chọn khối--";
            kl.idTruong = idTruong;
            kl.NamHoc = namhoc;
            khois.Insert(0, kl);

            ViewBag.khoi = khois;
            ViewBag.namhientai = namhoc;

            var lophoc = (from lh in db.LopHocs
                          join ul in db.Users_LopHoc
                          on new { lh.MaLop } equals new { ul.MaLop }
                          where lh.idTruong == idTruong && lh.NamHoc == namhoc && ul.UserName == userName && ul.idTruong == idTruong && ul.NamHoc == namhoc
                          select new LopHocGiaoVien
                          {
                              MaLop = lh.MaLop,
                              TenLop = lh.TenLop,
                              IdTruong = lh.idTruong,
                              NamHoc = lh.NamHoc
                          }).Distinct().ToList();
            LopHocGiaoVien lhoc = new LopHocGiaoVien();
            lhoc.MaLop = "";
            lhoc.TenLop = "--Chọn lớp học--";
            lhoc.NamHoc = namhoc;
            lhoc.IdTruong = idTruong;
            lophoc.Insert(0, lhoc);

            ViewBag.lophoc = lophoc;

            ViewBag.hocky = Cmon.CreateHocKy();

            //Cmon.listMonHoc = (from mh in db.DM_MonHoc select mh).ToList();


            return View(@"~/Views/TongHop/TongHopNhanXetHocSinh.cshtml");
        }

        public string getHoTen(String maHocSinh, int idTruong, string maLop, string namHoc)
        {
            return (from hocsinh in db.HocSinhs
                    where hocsinh.idTruong == idTruong && hocsinh.MaLop == maLop && hocsinh.NamHoc == namHoc && hocsinh.MaHocSinh == maHocSinh
                    select hocsinh).FirstOrDefault().HoTen.ToString();
        }

        [HttpPost]
        [Authorize]
        public ActionResult saveKhenThuong(string ngayKhen, string noidung, string khenThuong, string khenThuongCT, int idtruong, string namhoc, string malop, string mahocsinh, string maHK)
        {
            string notice = "OK";
            // string userName = User.Identity.Name.ToString() == "" ? "superadmin" : User.Identity.Name.ToString();
            string ngayKt = ngayKhen.Split('/')[2] + "-" + ngayKhen.Split('/')[1] + "-" + ngayKhen.Split('/')[0];
            DateTime ngayK = DateTime.Parse(ngayKt);
            var hocsinhkt = (from kt in db.HocSinh_KhenThuongKyLuat
                             where kt.idTruong == idtruong && kt.NamHoc == namhoc
                             && kt.MaLop == malop && kt.MaHocSinh == mahocsinh
                             && kt.Ngay == ngayK
                             select kt).FirstOrDefault();
            if (hocsinhkt != null)
            {
                notice = "NOT";
            }
            else
            {

                try
                {

                    HocSinh_KhenThuongKyLuat hocSinhKhenThuongKyLuat = new HocSinh_KhenThuongKyLuat();
                    hocSinhKhenThuongKyLuat.MaHocSinh = mahocsinh;
                    hocSinhKhenThuongKyLuat.MaHocSinhFriendly = mahocsinh;
                    hocSinhKhenThuongKyLuat.KhenThuong = khenThuong != null && khenThuong == "1" ? true : false;
                    hocSinhKhenThuongKyLuat.NoiDung = noidung;
                    hocSinhKhenThuongKyLuat.KhenThuongCapTruong = khenThuongCT != null && khenThuongCT == "1" ? true : false;

                    hocSinhKhenThuongKyLuat.MaLop = malop;
                    hocSinhKhenThuongKyLuat.idTruong = idtruong;
                    hocSinhKhenThuongKyLuat.Ngay = DateTime.ParseExact(ngayKhen, "dd/MM/yyyy", null);
                    hocSinhKhenThuongKyLuat.NamHoc = namhoc;
                    hocSinhKhenThuongKyLuat.MaHocKy = maHK;
                    hocSinhKhenThuongKyLuat.HoTen = getHoTen(mahocsinh, idtruong, malop, namhoc);

                    db.HocSinh_KhenThuongKyLuat.AddObject(hocSinhKhenThuongKyLuat);
                    db.SaveChanges();
                }
                catch (Exception ex)
                {

                }
            }

            return new JqGridJsonResult() { Data = notice };
        }

        [HttpGet]
        [Authorize]

        public JsonResult XoaMotKhenThuong(string maHS, string maLop, string namHoc, int idTruong, string hocKy, string ngay)
        {
            string mess = "";

            string username = getUserName();
            DateTime ngayTruyVan = DateTime.ParseExact(ngay, "dd/MM/yyyy", null);
            var kt = (from khenThuong in db.HocSinh_KhenThuongKyLuat.Where(t => t.idTruong == idTruong && t.NamHoc == namHoc && t.MaLop == maLop
                && t.MaHocSinh == maHS && t.Ngay == ngayTruyVan)
                      select khenThuong).FirstOrDefault();
            if (kt != null)
            {

                db.HocSinh_KhenThuongKyLuat.DeleteObject(kt);
                int del = db.SaveChanges();
                if (del > 0)
                    mess = "OK";
                else
                    mess = "Xóa tiêu chí không thành công!";
            }
            else
            {
                mess = "Không có thông tin để xóa!";
            }
            return Json(mess, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        [Authorize]

        public JsonResult XoaToanBoKhenThuong(string maHS, string maLop, string namHoc, int idTruong, string hocKy)
        {
            string mess = "";

            string username = getUserName();

            var kt = (from khenThuong in db.HocSinh_KhenThuongKyLuat.Where(t => t.idTruong == idTruong && t.NamHoc == namHoc && t.MaLop == maLop
                && t.MaHocSinh == maHS)
                      select khenThuong).FirstOrDefault();
            if (kt != null)
            {

                db.HocSinh_KhenThuongKyLuat.DeleteObject(kt);
                int del = db.SaveChanges();
                if (del > 0)
                    mess = "OK";
                else
                    mess = "Xóa tiêu chí không thành công!";
            }
            else
            {
                mess = "Không có thông tin để xóa!";
            }
            return Json(mess, JsonRequestBehavior.AllowGet);
        }



        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize]
        public ActionResult DanhSachHocSinhLopHoc(string maLop)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Thongbao");

            }
            string userName = getUserName();
            int idTruong = Cmon.getIdtruong(userName, db);
            string namHoc = Cmon.GetNamHienTai(idTruong);

            var danhsach = (from hs in db.HocSinhs
                            where hs.idTruong == idTruong && hs.NamHoc == namHoc && hs.MaLop == maLop
                            && !(from hsqt in db.HocSinh_QuaTrinh.Where(hsqt => hsqt.idTruong == idTruong && hsqt.NamHoc == namHoc && hsqt.MaLop == maLop && hsqt.MaQuaTrinh == "BH")
                                 select hsqt.MaHocSinh).Contains(hs.MaHocSinh)
                            orderby hs.STT ascending
                            select new ThongTinHocSinh
                            {
                                STT = hs.STT,
                                maHS = hs.MaHocSinh,
                                hoTenHS = hs.HoTen

                            }
                            ).ToList();

            return PartialView(@"~/Views/TongHop/TemplateHocSinh.cshtml", danhsach);
        }


        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize]
        public ActionResult GetDiemHocSinh(string maHs, string maLop, string hocKy)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Thongbao");

            }

            string userName = getUserName();
            int idTruong = Cmon.getIdtruong(userName, db);
            string namHoc = Cmon.GetNamHienTai(idTruong);
            string hoTenHs = Cmon.getHoTenHocSinh(maHs, idTruong, maLop, namHoc);

            short maKy = (short)Int64.Parse(hocKy);
            string maHocKy = hocKy == "0" ? "HK1" : "HK2";
            var diemMonHoc = (from monhoc in db.ASSIGN_LOP_MonHoc
                              join hs in db.HocSinh_Diem_NhanXet

VnEduPlus/Views/TongHop/1ViewThongKe.cshtml
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <meta charset="utf-8" />
    <title>jQuery UI Autocomplete - Combobox</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/uploadify.css")" rel="stylesheet" type="text/css" media="screen" />
    <link rel="stylesheet" href="@Url.Content("~/css/bootstrap/bootstrap.min.css")">
    <!-- Trung lam -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="@Url.Content("~/menucss/normalize.css")">
    <link rel="stylesheet" href="@Url.Content("~/menucss/stylemenu.css")">
    <!-- bootstrap ---------------------------------------------------------------->
    <link rel="stylesheet" href="@Url.Content("~/css/bootstrap/bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/throbber.css")" type="text/css">
    <script src="@Url.Content("~/js/bootstrap/js/bootstrap.min.js")"></script>
    <!-------------edu css-------------------------------------------------------->
    <script type="text/javascript">
        $(document).ready(function () {
            $("#btnReport").click(function () {
                var isCheckDiem = $('#chkLoaiBaoCaoDiem').prop('checked');
                var isCheckChatLuong = $('#chkLoaiBaoCaoChatLuong').prop('checked');
                if (isCheckDiem == true && isCheckChatLuong==false)
                {
                    ThongKeDiemKiemTra();
                }
                else {
                    ThongKeChatLuong();
                }
            });

            $("#exportExcell").click(function () {
                var isCheckDiem = $('#chkLoaiBaoCaoDiem').prop('checked');
                var isCheckChatLuong = $('#chkLoaiBaoCaoChatLuong').prop('checked');
                if (isCheckDiem == true && isCheckChatLuong == false) {
                    ThongKeDiemKiemTraExcel();
                }
                else {
                    ThongKeChatLuongExcel();
                }
            });
            $("#chkLoaiBaoCaoDiem").change(function () {
                var isCheckDiem = $('#chkLoaiBaoCaoDiem').prop('checked');
                if(isCheckDiem==true)
                    $('#chkLoaiBaoCaoChatLuong').prop('checked', false);
            });
            $("#chkLoaiBaoCaoChatLuong").change(function () {
                var isCheckChatLuong = $('#chkLoaiBaoCaoChatLuong').prop('checked');
                if (isCheckChatLuong == true)
                    $('#chkLoaiBaoCaoDiem').prop('checked', false);
            });
        });

        function ThongKeChatLuongExcel() {
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("ThongKeChatLuongExcel", "TongHopDanhGia")',
                data: {},
                beforeSend: function () {
                    $('#loading').css("display", "inherit");
                },
                success: function (data) {
                    $('#loading').css("display", "none");
                    window.location = '/TongHopDanhGia/DownloadFile?file=' + data;

                    return false;
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    $('#loading').css("display", "none");
                    alert('Failed to retrieve specification options.')
                    return false;
                }
            });
        }

        function ThongKeDiemKiemTraExcel()
        {
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("ThongKeDiemKiemTraExcel", "TongHopDanhGia")',
                data: {},
                beforeSend: function () {
                    $('#loading').css("display", "inherit");
                },
                success: function (data) {
                    $('#loading').css("display", "none");
                    window.location = '/TongHopDanhGia/DownloadFile?file=' + data;

                    return false;
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    $('#loading').css("display", "none");
                    alert('Failed to retrieve specification options.')
                    return false;
                }
            });
        }

        function ThongKeChatLuong()
        {
            $('#btnReport').attr("disabled", "disabled");
            var MaHocKy = $("#maHocKy").val();
            var NamHoc = $("#NamHoc").val();
            debugger;
            $.ajax({
                cache: true,
                type: 'GET',
                url: '@Url.Action("ThongKeChatLuong", "TongHopDanhGia")',
                data: { MaHocKy: MaHocKy, NamHoc: NamHoc },
                beforeSend: function () {
                    $('#loading').css("display", "inherit");
                },
                success: function (data) {
                    $('#exportExcell').removeAttr("disabled");
                    $('.throbber-loader.edu-spinner-loader').hide();
                    $("#containerReport").empty();
                    $("#containerReport").html(data);
                    $('#btnReport').removeAttr("disabled");
                    $('#loading').css("display", "none");
                },

                error: function (xhr, ajaxOptions, thrownError) {
                    $('#loading').css("display", "none");
                    alert('Hết phiên làm việc, đề nghị đăng nhập trở lại.')
                }

            });
        }

        function ThongKeDiemKiemTra()
        {
            $('#btnReport').attr("disabled", "disabled");
            var MaHocKy = $("#maHocKy").val();
            var NamHoc = $("#NamHoc").val();
            debugger;
            $.ajax({
                cache: true,
                type: 'GET',
                url: '@Url.Action("ThongKeDiemKiemTra", "TongHopDanhGia")',
                data: { MaHocKy: MaHocKy, NamHoc: NamHoc },
                beforeSend: function () {
                    $('#loading').css("display", "inherit");
                },
                success: function (data) {
                    $('#exportExcell').removeAttr("disabled");
                    $("#containerReport").empty();
                    $("#containerReport").html(data);
                    $('#btnReport').removeAttr("disabled");
                    $('#loading').css("display", "none");
                    //alert(data);
                },

                error: function (xhr, ajaxOptions, thrownError) {
                    $('#loading').css("display", "none");
                    alert('Hết phiên làm việc, đề nghị đăng nhập trở lại.')
                }

            });
        }
    </script>
</head>
@RenderPage("~/Views/Shared/_MainMenu.cshtml");
<div id="loading" style="position:absolute;padding-top: 220px;width: 100%;text-align: center; display:none" class="fa fa-refresh fa-spinner"><img src="../../Images/loading.gif" /></div>
<div style="margin-top: 20px; width: 100% !important">
    
    <table style="border: 0px; background: #fff; width: 100%;">

        <tr>
            <td style="border: 0px; padding: 25px 0px 0px 0px; font-size:16px; font-weight: bolder; text-transform: uppercase" align=center>
                <strong>Báo cáo thống kê Năm học @ViewBag.namhientai <input type="hidden" id="NamHoc" value="@ViewBag.namhientai"/> </strong>
            </td>
        </tr>
        <tr>
            <td align=center>
                Chọn thống kê theo điểm: <input id="chkLoaiBaoCaoDiem" type="checkbox" checked="checked"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                Chọn thống kê theo chất lượng: <input id="chkLoaiBaoCaoChatLuong" type="checkbox"/>
           </td>
        </tr>
        <tr>
            <td style="border: 0px; text-align: center;padding-top: 10px; width: 100%" id="fisrtline">
                <table border="0" style="background:#fff; text-align:center; width: 100%">
                    <tr valign="top">
                        
                        <td style="border: 0px; text-align: center;">
                            Chọn học kỳ: &nbsp;
                        

                            @Html.DropDownList("maHocKy", ViewBag.hocKyMacDinh as SelectList, new { @style= "height: 34px;" })
                            <button style="height: 34px" type="button" id="btnReport" class="btn btn-primary btn-sm" data-toggle="modal">Xem</button>
                            <button type="button" id="exportExcell" class="btn btn-info" disabled data-toggle="modal">Xuất Excel</button>
                        
                        </td>
        

                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                
            </td>
        </tr>
    </table>
    <div id="containerReport" style="width:100%; padding-top: 40px; padding: 0 3px">

    </div>
    @*<div id="ThongKeChatLuong">
        <div id="TKChatLuongHocTap">

        </div>
        <div id="TKChatLuongNangLuc">

        </div>
        <div id="TKChatLuongPhamChat">

        </div>
        <div id="TKChatLuongKhac">

        </div>
    </div>*@
    
    <input type="hidden" id="idtruong" name="idtruong" value="@ViewBag.idTruong" />
    
</div>

VnEduPlus/Views/TongHop/TemplateHocSinh123.cshtml
@model IList<VnEduPlus.Models.ThongTinHocSinh>

  <script type="text/javascript">
    //Todo
      $(document).ready(function () {

          $('#dshs a').click(function () {
              console.log(this.id);
              var maHS = this.id;
              var maLop = $('#lophoc').val();
              var hocKy = $('#hocky').val();
              
              $('#mahs').val(maHS);
              $('#btnMacDinh').show();
              if (maHS != null && maLop != null && hocKy != "-1")
                  $.ajax({
                      cache: true,
                      type: 'GET',
                      url: '@Url.Action("GetDiemHocSinh", "TongHopDanhGia")',
                      data: { maHs: maHS, maLop: maLop, hocKy: hocKy },
                      success: function (data) {
                          $("#contentnx").empty();
                          $("#contentnx").html(data);

                      },

                      error: function (xhr, ajaxOptions, thrownError) {
                          alert('Failed to retrieve specification options.')
                      }

                  });


          });


      });


   </script>
   <input type="hidden" id="mahs" value="" />



  <table style="margin-top: 135px; width: 100%;">
    <thead>
      <tr>
        <th style="border: 1px solid #ccc; text-align: center;">STT</th>
        <th style="border: 1px solid #ccc; text-align: center;">Họ Tên</th>
      </tr>
    </thead>
    <tbody>
    @{for(int i=0; i<Model.Count; i++)
      {
        <tr>
            <td style="border: 1px solid #ccc; text-align: center;">@Model[i].STT</td>
            <td style="border: 1px solid #ccc;padding: 5px;"><a href="#" id="@Model[i].maHS">@Model[i].hoTenHS</a></td>
        </tr>
      }
    }
    </tbody>
  </table>

VnEduPlus/Views/TongHop/ViewThongKeSoLieu.cshtml
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <meta charset="utf-8" />
    <title>jQuery UI Autocomplete - Combobox</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/uploadify.css")" rel="stylesheet" type="text/css" media="screen" />
    <link rel="stylesheet" href="@Url.Content("~/css/bootstrap/bootstrap.min.css")">
    <!-- Trung lam -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="@Url.Content("~/menucss/normalize.css")">
    <link rel="stylesheet" href="@Url.Content("~/menucss/stylemenu.css")">
    <!-- bootstrap ---------------------------------------------------------------->
    <link rel="stylesheet" href="@Url.Content("~/css/bootstrap/bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/css/throbber.css")" type="text/css">
    <script src="@Url.Content("~/js/bootstrap/js/bootstrap.min.js")"></script>
    <!-------------edu css-------------------------------------------------------->
    <script type="text/javascript">
        $(document).ready(function () {
            $("#btnReport").click(function () {
                ThongKeSoLieuHocSinh();
            });

            $("#exportExcell").click(function () {
                ThongKeSoLieuHocSinhExcel();
            });
        });

        function ThongKeSoLieuHocSinhExcel()
        {
            $.ajax({
                cache: false,
                type: "GET",
                url: '@Url.Action("ThongKeSoLieuExcel", "TongHopDanhGia")',
                data: {},
                beforeSend: function () {
                    $('#loading').css("display", "inherit");
                },
                success: function (data) {
                    $('#loading').css("display", "none");
                    if (data != 'NoData')
                    {
                        window.location = '/TongHopDanhGia/DownloadFile?file=' + data;
                    }
                    else {
                        alert('Không có dữ liệu để xuất báo cáo.')
                    }

                    return false;
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    $('#loading').css("display", "none");
                    alert('Failed to retrieve specification options.')
                    return false;
                }
            });
        }

        function ThongKeSoLieuHocSinh()
        {
            $('#btnReport').attr("disabled", "disabled");
            var NamHoc = $("#NamHoc").val();
            var MaKhoi = $("#makhoi").val();
            debugger;
            $.ajax({
                cache: true,
                type: 'GET',
                url: '@Url.Action("BaoCaoThongKeSoLieuHocSinh", "TongHopDanhGia")',
                data: { NamHoc: NamHoc, MaKhoi: MaKhoi },
                beforeSend: function () {
                    $('#loading').css("display", "inherit");
                },
                success: function (data) {
                    $('#exportExcell').removeAttr("disabled");
                    $('.throbber-loader.edu-spinner-loader').hide();
                    $("#containerReport").empty();
                    $("#containerReport").html(data);
                    $('#btnReport').removeAttr("disabled");
                    $('#loading').css("display", "none");
                },

                error: function (xhr, ajaxOptions, thrownError) {
                    $('#loading').css("display", "none");
                    alert('Hết phiên làm việc, đề nghị đăng nhập trở lại.')
                }

            });
        }

        
    </script>
</head>
@RenderPage("~/Views/Shared/_MainMenu.cshtml");
<div id="loading" style="position:absolute;padding-top: 220px;width: 100%;text-align: center; display:none" class="fa fa-refresh fa-spinner"><img src="../../Images/loading.gif" /></div>
<div style="margin-top: 20px; width: 100% !important">
    
    <table style="border: 0px; background: #fff; width: 100%;">

        <tr>
            <td style="border: 0px; padding: 25px 0px 0px 0px; font-size:16px; font-weight: bolder; text-transform: uppercase" align=center>
                <strong>THỐNG KÊ SỐ LIỆU HỌC SINH NĂM HỌC @ViewBag.namhientai <input type="hidden" id="NamHoc" value="@ViewBag.namhientai"/> </strong>
            </td>
        </tr>
        <tr>
            <td style="border: 0px; font-size:13; text-transform: uppercase" align=center>
                Khối: @Html.DropDownList("makhoi", "Toàn trường")
                      <button style="height: 34px" type="button" id="btnReport" class="btn btn-primary btn-sm" data-toggle="modal">Xem</button>
                      <button type="button" id="exportExcell" class="btn btn-info" disabled data-toggle="modal">Xuất Excel</button>
                        
            </td>


        </tr>
        <!--
        <tr>
            <td style="border: 0px; text-align: center;padding-top: 10px; width: 100%" id="fisrtline">
                <table border="0" style="background:#fff; text-align:center; width: 100%">
                    <tr valign="top">
                        
                        <td style="border: 0px; text-align: center;">
                            
                            <button style="height: 34px" type="button" id="btnReport" class="btn btn-primary btn-sm" data-toggle="modal">Xem</button>
                            <button type="button" id="exportExcell" class="btn btn-info" disabled data-toggle="modal">Xuất Excel</button>
                        
                        </td>
        

                    </tr>
                </table>
            </td>
        </tr>
        -->
        <tr>
            <td>
                
            </td>
        </tr>
    </table>
    <div id="containerReport" style="width:100%; padding-top: 40px; padding: 0 3px">

    </div>
    <br />
    @*<div id="ThongKeChatLuong">
        <div id="TKChatLuongHocTap">

        </div>
        <div id="TKChatLuongNangLuc">

        </div>
        <div id="TKChatLuongPhamChat">

        </div>
        <div id="TKChatLuongKhac">

        </div>
    </div>*@
    
    <input type="hidden" id="idtruong" name="idtruong" value="@ViewBag.idTruong" />
    
</div>