VnEduPlus/Controllers/PhieuLienLacController.cs
using System;
using System.Collections.Generic;
using System.Data.Objects;
using System.Linq;
using System.Web.Mvc;
using VnEduPlus.CmonFunction;
using VnEduPlus.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
 


namespace VnEduPlus.Controllers
{
    /// <summary>
    /// Chuc nang nay se thuc hien tao ra cac report phuc vu cho cac chuc nang khac nhau 
    /// </summary>
    public class PhieuLienLacController : Controller
    {
        //
        // GET: /ReportResult/
        EDUNP_CAP1Entities db = new EDUNP_CAP1Entities();


        private string GetUserName()
        {
            string userName = User.Identity.Name.ToString() == "" ? "superadmin" : User.Identity.Name.ToString();
            return userName;
        }

        private void GetKhoangTG(string hocky, string namhoc, int idTruong, out DateTime? ngayBD, out DateTime? ngayKT)
        {
            ngayBD = null;
            ngayKT = null;
           // if (hocky == "CN")// neu la thoi gian ca nam thi se lay ngay bat dau hoc la ngay bat dau hoc ky 1 va ngay ket thu la ngay ket thuc hoc ky 2
            if (hocky == "HK2")// neu la thoi gian ca nam thi se lay ngay bat dau hoc la ngay bat dau hoc ky 1 va ngay ket thu la ngay ket thuc hoc ky 2
            {
                ngayBD = (DateTime)db.DM_HocKy.Where(hk => hk.MaHocKy == "HK1" &&
                                              hk.NamHoc == namhoc && hk.idTruong == idTruong).FirstOrDefault().NgayBatDau;

                ngayKT = (DateTime)db.DM_HocKy.Where(hk => hk.MaHocKy == "HK2" &&
                                              hk.NamHoc == namhoc && hk.idTruong == idTruong).FirstOrDefault().NgayKetThuc;


            }
            else
            {

                var mahocky = db.DM_HocKy.Where(hk => hk.MaHocKy == hocky &&
                                                hk.NamHoc == namhoc && hk.idTruong == idTruong).SingleOrDefault();
                if (mahocky != null)
                {
                    ngayBD = mahocky.NgayBatDau;
                    ngayKT = mahocky.NgayKetThuc;
                }
            }
        }

        private static string GetTenHocKy(string hocky)
        {
            string tenhocky = "";
            if (hocky == "K1" || hocky == "HKI" || hocky == "HK1")
            {
                tenhocky = "Học kỳ I";
            }
            else if (hocky == "K2" || hocky == "HKII" || hocky == "HK2")
            {
                tenhocky = "Học kỳ II";
            }
            else tenhocky = "Cả năm";
            return tenhocky;
        }


        /// <summary>
        /// Thông kê tổng hợp giáo dục
        /// </summary>
        /// <param name="namhoc"></param>
        /// <param name="idTruong"></param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize]
        public ActionResult SoLienLac()
        {
            if (Request.IsAuthenticated)
            {

                string userName = GetUserName();
                ScrUser user = (from us in db.ScrUsers
                                where us.UserName == userName
                                select us).FirstOrDefault();

                int idTruong = user.idTruong != null ? (int)user.idTruong : 26;
                string namhoc = Cmon.GetNamHienTai(idTruong);
                bool isHieuTruong = Cmon.isHieuTruong(idTruong, userName);
                ViewBag.isHieuTruong = isHieuTruong;
                ViewBag.loaiNhapDiem = Cmon.checkLoaiNhapDiemCuaTruong(idTruong);
                ViewBag.style = Cmon.checkFormNhapDiemCuaTruong(idTruong);
                var listkhoi = (from khoi in db.DM_Khoi
                                let makhoiList = from lophoc in db.LopHocs
                                                 join userlh in db.Users_LopHoc on lophoc.MaLop equals userlh.MaLop
                                                 where userlh.UserName == userName && userlh.idTruong == idTruong && userlh.NamHoc == namhoc
                                                 select lophoc.MaKhoi
                                where makhoiList.Contains(khoi.MaKhoi) && khoi.idTruong == idTruong && khoi.NamHoc == namhoc
                                select khoi).ToList();

                ViewBag.makhoi = new SelectList(listkhoi, "MaKhoi", "TenKhoi");
                ViewBag.malop = new SelectList(new List<LopHoc>(), "MaLop", "TenLop", null);
                ViewBag.tentruong = Cmon.GetnameSchool(idTruong);
                ViewBag.tendangnhap = Cmon.GetnameUserName(userName, idTruong);
                ViewBag.namhoc = namhoc;
                ViewBag.idtruong = idTruong;
                var listhocky = db.DM_HocKy.Where(hk => hk.idTruong == idTruong && hk.NamHoc == namhoc).ToList();
                string path = Server.MapPath("~/PhieuLienLac_Template.xls");
                string p2 = HttpContext.Server.MapPath("~/PhieuLienLac_Template.xls");
                ViewBag.path1 = path;
                ViewBag.path2 = p2;



                return View();
            }
            else
            {

                return RedirectToAction("Index", "Thongbao");
            }
        }
        
        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult LoadLophoc(string id, string namhoc, int idTruong)
        {
            string userName = GetUserName();

           var listlophoc = (from lop in db.LopHocs
                             where lop.idTruong == idTruong && lop.NamHoc == namhoc && lop.MaKhoi == id
                             let allowlops =
                             ( 
                             from userLop in db.Users_LopHoc.Where(userLop => userLop.idTruong == idTruong && userLop.NamHoc == namhoc && userLop.UserName == userName)
                             
                             select userLop.MaLop)
                             where allowlops.Contains(lop.MaLop) && lop.MaKhoi == id && lop.NamHoc == namhoc
                             select new SelectListItem()
                             {
                                 Value = lop.MaLop,
                                 Text = lop.TenLop,

                             }).ToList();


            return Json(listlophoc, JsonRequestBehavior.AllowGet);

        }

        [AcceptVerbs(HttpVerbs.Get)]
        public JsonResult LoadMonHocTheoLop(string malop, string namhoc, int idTruong)
        {
            string userName = User.Identity.Name.ToString() == "" ? "superadmin" : User.Identity.Name.ToString();

            var listMonhoc = (from userlop in db.Users_Monhoc.Where(userlop => userlop.MaLop == malop && userlop.NamHoc == namhoc && userlop.idTruong == idTruong)
                              join dmmonhoc in db.DM_MonHoc on userlop.MaMonHoc equals dmmonhoc.MaMonHoc
                              select new SelectListItem()
                              {
                                  Value = userlop.MaMonHoc,
                                  Text = dmmonhoc.TenMonHoc,

                              }).ToList();


            return Json(listMonhoc, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// He thong tam thoi dang lay namhoc la nam hien tai cua he thong
        /// </summary>
        /// <param name="hocky"></param>
        /// <param name="malop"></param>
        /// <returns></returns>
        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize]
        public ActionResult ketQuaHocTap(string malop, string hocky, string namhoc, int idTruong, string tentruong, string tengiaovien, bool exportExcel = false)
        {
            if (!Request.IsAuthenticated)
            {

                return RedirectToAction("Index", "Thongbao");
            }
            else
            {


                ViewBag.hocky = GetTenHocKy(hocky);
                ViewBag.namhoc = namhoc;
                ViewBag.tentruong = tentruong;
                ViewBag.tengiaovien = tengiaovien;

                var lop = db.LopHocs.Where(l => l.MaLop == malop && l.idTruong == idTruong && l.NamHoc == namhoc).SingleOrDefault();
                ViewBag.tenlop = lop.TenLop;

                if (exportExcel)
                {
                    Response.AddHeader("Content-Type", "application/vnd.ms-excel");
                    ViewBag.exportExcel = true;
                }

                DateTime? ngayBD;
                DateTime? ngayKT;
                GetKhoangTG(hocky, namhoc, idTruong, out ngayBD, out ngayKT);

                // lay danh sach hoc sinh cua lop dua len
                var listketquahoctap = (from hs in db.HocSinhs.Where(hs => hs.idTruong == idTruong && hs.MaLop == malop && hs.NamHoc == namhoc)
                                        join kq in db.HocSinh_TongHopNX.Where(kq => kq.idTruong == idTruong && kq.NamHoc == namhoc && kq.MaLop == malop)
                                        on hs.MaHocSinh equals kq.MaHocSinh
                                        into join1

                                        from j1 in join1.DefaultIfEmpty()
                                        join hk in db.HocSinh_HanhKiemTongKet.Where(hk => hk.idTruong == idTruong && hk.NamHoc == namhoc && hk.MaLop == malop)
                                        on hs.MaHocSinh equals hk.MaHocSinh
                                        into join2

                                        from j2 in join2.DefaultIfEmpty()

                                        select new ThongKeKetQuaHocTap
                                        {
                                            mahocsinh = hs.MaHocSinh,
                                        }

                            ).ToList();


                return View(listketquahoctap);


            }

        }


        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize]
        public ActionResult LoadDanhSachHocSinh(int idtruong, string malop,string namhoc)
        {

VnEduPlus/Views/PhieuLienLac/BiaSoLienLac.cshtml
@model List<VnEduPlus.Models.DiemTheoMonHoc>
<style type="text/css">
    table td
    {
        border: 1px solid #CCCCCC;
    }
</style>

@{
    if (ViewBag.exportExcel != null && ViewBag.exportExcel == true) 
    {
         Layout = "~/Views/Shared/_LayoutExcel.cshtml";
    }
}

<table width="100%" style="border: 1px solid gray;">
   <tr>
    <td><strong>S&#7902; GI&Aacute;O D&#7908;C V&Agrave; &#272;&Agrave;O T&#7840;O TH&Agrave;NH PH&#7888; &#272;&Agrave; N&#7860;NG </strong></td>
    <td>&nbsp;</td>
    <td><strong>C&#7897;ng h&ograve;a x&atilde; h&#7897;i ch&#7911; ngh&#297;a Vi&#7879;t nam </strong></td>
  </tr>
  <tr>
    <td><strong>TR&#431;&#7900;NG @ViewBag.tentruong</strong></td>
    <td>&nbsp;</td>
    <td><strong>&#272;&#7897;c l&#7853;p- T&#7921; Do- H&#7841;nh ph&uacute;c </strong></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="3"><div align="center"><strong>TH&#7888;NG K&Ecirc; CH&#7844;T L&#431;&#7906;NG B&Agrave;I KI&#7874;M TRA  @ViewBag.hocky - N&#258;M H&#7884;C @ViewBag.namhoc</strong></div></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="3"><div align="center"><strong>M&ocirc;n h&#7885;c @ViewBag.tenmonhoc </strong></div></td>
  </tr>
  <tr>
    <td colspan="3"><table width="100%" border="0">
      <tr>
        <td width="4%" rowspan="2"><div align="center"><strong>L&#7899;p</strong></div></td>
        <td width="7%" rowspan="2"><div align="center"><strong>T&#7893;ng s&#7893; H/S </strong></div></td>
        <td colspan="2"><div align="center"><strong>&#272;i&#7875;m =0 </strong></div></td>
        <td colspan="2"><div align="center"><strong>0&lt;&#272;i&#7875;m &lt;2</strong></div></td>
        <td colspan="2"><div align="center"><strong>2&lt;&#272;i&#7875;m &lt;4</strong></div></td>
        <td colspan="2"><div align="center"><strong>4&lt;&#272;i&#7875;m &lt;5</strong></div></td>
        <td colspan="2"><div align="center"><strong>5&lt;&#272;i&#7875;m &lt;7</strong></div></td>
        <td colspan="2"><div align="center"><strong>7&lt;&#272;i&#7875;m &lt;8</strong></div></td>
        <td colspan="2"><div align="center"><strong>8&lt;&#272;i&#7875;m &lt;10</strong></div></td>
        <td colspan="2"><div align="center"><strong>&#272;i&#7875;m =10 </strong></div></td>
        <td colspan="2"><div align="center"><strong>Ch&#432;a c&oacute; &#273;i&#7875;m </strong></div></td>
        <td colspan="2"><div align="center"><strong>Tr&ecirc;n TB </strong></div></td>
        </tr>
      <tr>
        <td width="5%"><div align="center"><strong>SL</strong></div></td>
        <td width="4%"><div align="center"><strong>T&#7881; l&#7879; </strong></div></td>
        <td width="5%"><div align="center"><strong>SL</strong></div></td>
        <td width="4%"><div align="center"><strong>T&#7881; l&#7879; </strong></div></td>
        <td><div align="center"><strong>SL</strong></div></td>
        <td><div align="center"><strong>T&#7881; l&#7879; </strong></div></td>
        <td><div align="center"><strong>SL</strong></div></td>
        <td><div align="center"><strong>T&#7881; l&#7879; </strong></div></td>
        <td><div align="center"><strong>SL</strong></div></td>
        <td><div align="center"><strong>T&#7881; l&#7879; </strong></div></td>
        <td><div align="center"><strong>SL</strong></div></td>
        <td><div align="center"><strong>T&#7881; l&#7879; </strong></div></td>
        <td><div align="center"><strong>SL</strong></div></td>
        <td><div align="center"><strong>T&#7881; l&#7879; </strong></div></td>
        <td><div align="center"><strong>SL</strong></div></td>
        <td><div align="center"><strong>T&#7881; l&#7879; </strong></div></td>
        <td><div align="center"><strong>SL</strong></div></td>
        <td><div align="center"><strong>T&#7881; l&#7879; </strong></div></td>
        <td><div align="center"><strong>SL</strong></div></td>
        <td><div align="center"><strong>T&#7881; l&#7879; </strong></div></td>
      </tr>
       @foreach (var item in Model)
       {
           double tileLoai1 = 0;
           double tiLeLoai2 = 0;
           double tiLeLoai3 = 0;
           double tiLeLoai4 = 0;
           double tiLeLoai5 = 0;

           double tiLeLoai6 = 0;
           double tiLeLoai7 = 0;
           double tiLeLoai8 = 0;
           double tiLeLoai9 = 0;
                      
           if (item.siso > 0)
           {
               tileLoai1 = System.Math.Round((double)item.level1 * 100 / (double)item.siso, 2, MidpointRounding.ToEven);
               tiLeLoai2 = System.Math.Round((double)item.level2 * 100 / (double)item.siso, 2, MidpointRounding.ToEven);
               tiLeLoai3 = System.Math.Round((double)item.level3 * 100 / (double)item.siso, 2, MidpointRounding.ToEven);
               tiLeLoai4 = System.Math.Round((double)item.level4 * 100 / (double)item.siso, 2, MidpointRounding.ToEven);
               tiLeLoai5 = System.Math.Round((double)item.level5 * 100 / (double)item.siso, 2, MidpointRounding.ToEven);
               tiLeLoai6 = System.Math.Round((double)item.level6 * 100 / (double)item.siso, 2, MidpointRounding.ToEven);
               tiLeLoai7 = System.Math.Round((double)item.level7 * 100 / (double)item.siso, 2, MidpointRounding.ToEven);
               tiLeLoai8 = System.Math.Round((double)item.level8 * 100 / (double)item.siso, 2, MidpointRounding.ToEven);
               tiLeLoai9 = System.Math.Round((double)item.level9 * 100 / (double)item.siso, 2, MidpointRounding.ToEven);
           }
           
      <tr>
        <td>@item.tenlop</td>
        <td>@item.siso</td>

        <td>@item.level1</td>
        <td>@tileLoai1</td>
        
        <td>@item.level2</td>
        <td>@tiLeLoai2</td>
        
        <td>@item.level3</td>
        <td>@tiLeLoai3</td>
        
        <td>@item.level4</td>
        <td>@tiLeLoai4</td>
        
        <td>@item.level5</td>
        <td>@tiLeLoai5</td>
        
        <td>@item.level6</td>
        <td>@tiLeLoai6</td>
        
        <td>@item.level7</td>
        <td>@tiLeLoai7</td>
        
        <td>@item.level8</td>
        <td>@tiLeLoai8</td>
        
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        
        <td>@item.level9</td>
        <td>@tiLeLoai9</td>
      </tr>
       }
    </table></td>
  </tr>
</table>

VnEduPlus/Views/PhieuLienLac/SoLienLac.cshtml
@{
    ViewBag.Title = "Phiếu liên lạc";
}

<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/js/jquery.dataTables.min.js")" type="text/javascript"></script>
<!-- Trung lam -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="stylesheet" href="@Url.Content("~/menucss/normalize.css")">
<link rel="stylesheet" href="@Url.Content("~/menucss/stylemenu.css")">
<link href="@Url.Content("~/css/jquery.dataTables.css")" rel="stylesheet" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet'
    type='text/css'>
<style type="text/css">
    .modal
    {
        display: none;
        position: fixed;
        z-index: 1000;
        top: 0;
        left: 0;
        height: 100%;
        width: 100%;
        background: rgba( 255, 255, 255, .8 ) url('http://i.stack.imgur.com/FhHRx.gif') 50% 50% no-repeat;
    }
    
    /* When the body has the loading class, we turn
   the scrollbar off with overflow:hidden */
    body.loading
    {
        overflow: hidden;
    }
    .dataTables_length
    {
        display:none;
        }
     .dataTables_info
     {
         display:none;
         }
    /* Anytime the body has the loading class, our
   modal element will be visible */
    body.loading .modal
    {
        display: block;
    }
</style>
<script type="text/javascript">

    $(document).ready(function () {

        var mkhoi = $("#makhoi").val();
        if (mkhoi != "") {
            loadDSLop(mkhoi);
        }

        $("#makhoi").change(function () {
            var mkhoi = $("#makhoi").val();
            loadDSLop(mkhoi);
        });


        $("#malop").change(function () {
            var mahk = $("#MaHocKy").val();
            if (mahk != '') {
                loadDSHocSinh();

            }
        });

        $("#MaHocKy").change(function () {
            loadDSHocSinh();
        });

        $("#exportExcel").click(function () {
            var makhoi = document.getElementById("makhoi").value;
            var malop = document.getElementById("malop").value;
            var mahocky = document.getElementById("MaHocKy").value;
            var namhoc = document.getElementById("namhoc").value;
            var idTruong = document.getElementById("idtruong").value;
            var tentruong = document.getElementById("tentruong").value;
            // var tengiaovien = document.getElementById("tengiaovien").value;

            var tab = document.getElementById("gvhocsinh")
            var chk = tab.getElementsByTagName("input");
            var num = chk.length;
            var idHocSinhList = "";
            for (var i = 0; i < num; i++) {
                status = chk[i].getAttribute("type");
                if (status == "checkbox") {
                    if (chk[i].checked == true) {
                        if (idHocSinhList == "") idHocSinhList = chk[i].id;
                        else idHocSinhList += "," + chk[i].id
                    }
                }
            }
            if (idHocSinhList == "")
                alert('Yêu cầu chọn ít nhất một học sinh để tạo sổ liên lạc!');
            else {
                var sohocsinh = idHocSinhList.split(',');
                var sohs = parseInt(sohocsinh.length);
                //                if (sohs > 5) {
                //                    alert('Yêu cầu chọn không quá 5 học sinh để tạo sổ liên lạc!');
                //                }
                //                else {var
                if (mahocky == "GHK1") {
                    window.location = '@Url.Action("SoLienLacXuatExcellGHK1", "PhieuLienLac")?idtruong=' + idTruong + '&makhoi=' + makhoi + '&malop=' + malop + '&mahk=' + mahocky + '&namhoc=' + namhoc + " &tentruong=" + tentruong + "&mahocsinh=" + idHocSinhList;
                } else if (mahocky == "HK1") {
                    window.location = '@Url.Action("SoLienLacXuatExcellHK1", "PhieuLienLac")?idtruong=' + idTruong + '&makhoi=' + makhoi + '&malop=' + malop + '&mahk=' + mahocky + '&namhoc=' + namhoc + " &tentruong=" + tentruong + "&mahocsinh=" + idHocSinhList;
                } else if (mahocky == "GHK2") {
                    window.location = '@Url.Action("SoLienLacXuatExcellGHK2", "PhieuLienLac")?idtruong=' + idTruong + '&makhoi=' + makhoi + '&malop=' + malop + '&mahk=' + mahocky + '&namhoc=' + namhoc + " &tentruong=" + tentruong + "&mahocsinh=" + idHocSinhList;
                } else if (mahocky == "HK2") {
                    window.location = '@Url.Action("SoLienLacXuatExcellHK2", "PhieuLienLac")?idtruong=' + idTruong + '&makhoi=' + makhoi + '&malop=' + malop + '&mahk=' + mahocky + '&namhoc=' + namhoc + " &tentruong=" + tentruong + "&mahocsinh=" + idHocSinhList;
                }
                
                // }
            }


        });

    });


    function loadDSHocSinh() {
        var malop = document.getElementById("malop").value;
        var namhoc = document.getElementById("namhoc").value;
        var idTruong = document.getElementById("idtruong").value;
        $.ajax({
            cache: false,
            type: "GET",
            url: '@Url.Action("LoadDanhSachHocSinh", "PhieuLienLac")',
            data: { idtruong: idTruong, malop: malop, namhoc: namhoc },
            success: function (data) {
                $("#viewdata").empty();
                $("#viewdata").html(data);

                $('#gvhocsinh').dataTable({
                    "bPaginate": false,
                    "bSort": true
                });
            },
            error: function (xhr, ajaxOptions, thrownError) {
                alert('Failed to retrieve specification options.')
            }
        });
    }

    function CheckNoOfHocSinh(obj) {
        var tab = document.getElementById("gvhocsinh")
        var chk = tab.getElementsByTagName("input");
        var num = chk.length;
        var idHocSinhList = "";
        for (var i = 0; i < num; i++) {
            status = chk[i].getAttribute("type");
            if (status == "checkbox") {
                if (chk[i].checked == true) {
                    if (idHocSinhList == "") idHocSinhList = chk[i].id;
                    else idHocSinhList += "," + chk[i].id
                }
            }
        }

        var sohocsinh = idHocSinhList.split(',');
        var sohs = parseInt(sohocsinh.length);
        if (sohs > 5) {
            alert('Yêu cầu chọn không quá 5 học sinh để tạo sổ liên lạc!');
            obj.checked = false;
        }
    }

    function loadDSLop(mkhoi) {

        var namhoc = document.getElementById("namhoc").value;
        var idTruong = document.getElementById("idtruong").value;

        var dlop = $("#malop");
        dlop.empty();

        $.getJSON('@Url.Action("LoadLophoc", "PhieuLienLac")', { id: mkhoi, namhoc: namhoc, idTruong: idTruong },
            function (khoiData) {
                var select = $("#malop");
                select.empty();
                select.append($('<option/>', {
                    value: 0,
                    text: "Chọn lớp"
                }));
                $.each(khoiData, function (Mainview, itemData) {
                    select.append($('<option/>', {
                        value: itemData.Value,
                        text: itemData.Text
                    }));
                });
            });
    }
     
</script>
<input type="hidden" id="idtruong" name="idtruong" value="@ViewBag.idtruong" />
<input type="hidden" id="tentruong" name="tentruong" value="@ViewBag.tentruong" />
<input type="hidden" id="namhoc" name="idtruong" value="@ViewBag.namhoc" />
<input type="hidden" id="tengiaovien" name="tengiaovien" value="@ViewBag.tendangnhap" />
@RenderPage("~/Views/Shared/_MainMenu.cshtml");
<table style="margin-top: 50px;" width="800" border="1" align="center">
    <tr>
        <td width="300">
            <br />
            <br />
            <strong>Trường</strong>:<strong> @*@ViewBag.tentruong
            duong dan : @ViewBag.path1 -- @ViewBag.path2*@
            
            </strong>
            <br />
            <strong>Năm học</strong>:<strong>@ViewBag.namhoc</strong>
            <table width="100%" border="1" cellpadding="5">
                <tr>
                    <td width="35%">
                        Khối
                    </td>
                    <td>@Html.DropDownList("makhoi", "Chọn khối")
                    </td>
                </tr>
                <tr>
                    <td width="35%">
                        Lớp
                    </td>
                    <td>@Html.DropDownList("malop", "Chọn lớp")
                    </td>
                </tr>
                <tr>
                    <td width="35%">
                        Điều kiện
                    </td>
                    <td>
                        <select id="MaHocKy" name="MaHocKy">
                            <option value="">Lựa chọn điều kiện</option>
                            <option value="GHK1">Giữa học kỳ 1</option>                            
                            <option value="HK1">Học kỳ 1</option>
                            <option value="GHK2">Giữa học kỳ 2</option>
                            <option value="HK2">Cả năm</option>
                            <!-- <option value="CN">Cả năm</option>-->
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                    </td>
                    <td colspan="2" align="center">
                        <input class="submit" type="submit" name="button" id="exportExcel" value="Xuất Excel" />
                    </td>
                </tr>
            </table>
        </td>
        <td width="500" valign="top">
            <br />
            <p>
                Hệ thống sẽ xuất ra excel theo mẫu đã định sổ liên lạc và số điểm cho từng học sinh
                ra file excell để phục vụ cho việc liên lạc giữa nhà trường và phụ huynh học sinh
            </p>
            <p>
                &nbsp;</p>
        </td>
    </tr>
</table>
<table style="margin-top: 0px; width: 100%">
    
    <tr>
        <td colspan="2" id="viewdata" align="center">
        </td>
    </tr>
</table>

VnEduPlus/Views/PhieuLienLac/ViewHocSinh.cshtml
@model IList<VnEduPlus.Models.ViewHocSinh>
<script>
    function SelectAll() {
        var tab = document.getElementById("gvhocsinh")
        var chk = tab.getElementsByTagName("input");
        var num = chk.length;
        var x = document.getElementById("chkSelectAll");
        if (x.checked == true) {
            for (var i = 0; i < num; i++) {
                status = chk[i].getAttribute("type");
                if (status == "checkbox") {
                    chk[i].checked = true;
                }
            }
        }
        else {
            for (var i = 0; i < num; i++) {
                status1 = chk[i].getAttribute("type");
                if (status1 == "checkbox") {
                    chk[i].checked = false;
                }
            }
        }
    }
    
</script>
<style type="text/css">
    table tr
    {
        
        padding-bottom: 2px;
        padding-top: 2px;
    }
    
    table tr td
    {
        padding-top: 4px;    
    }
</style>
<table id="gvhocsinh" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th><input type="checkbox" id="chkSelectAll" onclick="javascript:SelectAll();" /></th>
            <th>
                Số thứ tự
            </th>
          @*  <th>
                Mã Học Sinh
            </th>*@
            <th>
                Họ Tên
            </th>
            <th>
                Giới tính
            </th>
            <th>
                Ngày sinh
            </th>
        </tr>
    </thead>
    <tbody>
    
        @{
            for (int i = 0; i < Model.Count; i++)
            {
                string id = Model[i].MaHocSinh;
            <tr>
                <td><input type="checkbox" @*onclick="javascript:CheckNoOfHocSinh(this)"*@ class="checkHocsinh" id="@id" /></td>
                <td>@Model[i].Stt</td>
              @*  <td>@Model[i].MaHocSinh
                </td>*@
                <td>@Model[i].HoTen
                </td>
                <td>@Model[i].GioiTinh
                </td>
                <td>
                @if (Model[i].NgaySinh.HasValue)
                { 
                    <text>@Model[i].NgaySinh.Value.ToString("dd/MM/yyyy")</text>
                }
                
                </td>
            </tr>
            }   
        }
    </tbody>
</table>

VnEduPlus/Views/PhieuLienLac/exportExcell.cshtml
@{
    ViewBag.Title = "exportExcell";
}

<h2>exportExcell</h2>