VnEduPlus/Controllers/GiaoVienBoMonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lib.Web.Mvc.JQuery.JqGrid;
using VnEduPlus.CmonFunction;
using VnEduPlus.Models;
using System.Globalization;
using System.Threading;
using System.Data.SqlClient;
using System.Data;

namespace VnEduPlus.Controllers
{
    public class GiaoVienBoMonController: Controller
    {
        EDUNP_CAP1Entities db = new EDUNP_CAP1Entities();
        /// <summary>
        /// lay username dang nhap 
        /// </summary>
        /// <returns></returns>
        public string getUserName()
        {
            return User.Identity.Name.ToString() == "" ? "superadmin" : User.Identity.Name.ToString();

        }

        #region Giáo viên bộ môn nhận xét thường xuyên

        [AcceptVerbs(HttpVerbs.Get)]
        [Authorize]
        public ActionResult GiaoVienBoMon()
        {
            // lay thong tin truong 
            string userName = getUserName();
            int idTruong = Cmon.getIdtruong(userName, db);
            string namhoc = Cmon.GetNamHienTai(idTruong);
            if (!Request.IsAuthenticated)
            {
                return View(@"~/Views/ThongBao/Index.cshtml");

            }



            bool isHieuTruong = Cmon.isHieuTruong(idTruong, userName);
            ViewBag.isHieuTruong = isHieuTruong;
            ViewBag.idtruong = idTruong;
            ViewBag.danhMucTieuChi = Cmon.createDanhMuc();
            ViewBag.danhmucMonHoc = listMonHoc(userName);
            ViewBag.danhMucThang = Cmon.createCacThangCoDinh(idTruong, db);


            ViewBag.loaiNhapDiem = Cmon.checkLoaiNhapDiemCuaTruong(idTruong);
            ViewBag.ShowDTBM = Cmon.checkShowOrHiddenDTBMCuaTruong(idTruong);
            ViewBag.style = Cmon.checkShowOrHiddenDTBMCuaTruong(idTruong);

            string namHoc = Cmon.GetNamHienTai(idTruong);
           
            ViewBag.namhientai = namhoc;
            ViewBag.tenuser = Cmon.GetnameUser(userName);

            var listkhoi = (from khoi in db.DM_Khoi
                            let makhoiList = from lophoc in db.LopHocs
                                             join userlh in db.Users_LopHoc on lophoc.MaLop equals userlh.MaLop
                                             where userlh.UserName == userName && userlh.idTruong == idTruong && userlh.NamHoc == namHoc
                                             select lophoc.MaKhoi
                            where makhoiList.Contains(khoi.MaKhoi) && khoi.idTruong == idTruong && khoi.NamHoc == namHoc
                            select khoi).ToList();

            if (listkhoi.Count()  == 0)
            {
                listkhoi = (from khoi in db.DM_Khoi
                             where khoi.idTruong == idTruong && khoi.NamHoc == namHoc
                            select khoi).ToList();

            }
            ViewBag.makhoi = new SelectList(listkhoi, "MaKhoi", "TenKhoi");


            return View();
        }

     
        [HttpGet]
        public JsonResult LoadMonHocTheoLop(string maLop)
        {
            string userName = getUserName();
            int idTruong = Cmon.getIdtruong(userName, db);
            string namhoc = Cmon.GetNamHienTai(idTruong);

            var lstMHQLLop = (from umh in db.Users_LopHoc.Where(t => t.UserName == userName && t.idTruong == idTruong && t.NamHoc == namhoc && t.MaLop == maLop)
                         join mh in db.ASSIGN_LOP_MonHoc on new { umh.idTruong, umh.MaLop} equals new { mh.idTruong, mh.MaLop}
                         select new DanhMucMonHoc
                         {
                             MaMon = mh.MaMonHoc.Trim(),
                             TenMon = mh.TenMonHoc
                         }
                         ).GroupBy(x => x.MaMon).Select(z => z.OrderBy(i => i.MaMon).FirstOrDefault()).ToList();
             
            var lstMH = (from umh in db.Users_Monhoc.Where(t => t.UserName == userName && t.idTruong == idTruong && t.NamHoc == namhoc && t.MaLop == maLop)
                         join mh in db.ASSIGN_LOP_MonHoc on new { umh.idTruong, umh.MaLop, umh.MaMonHoc } equals new { mh.idTruong, mh.MaLop, mh.MaMonHoc }
                         select new DanhMucMonHoc
                         {
                             MaMon = mh.MaMonHoc.Trim(),
                             TenMon = mh.TenMonHoc
                         }
                          ).GroupBy(x => x.MaMon).Select(z => z.OrderBy(i => i.MaMon).FirstOrDefault()).ToList();
            //DanhMucMonHoc dmnh = new DanhMucMonHoc();
            //dmnh.MaMon = "-1";
            //dmnh.TenMon = "--Chọn môn học--";
            //lstMH.Insert(0, dmnh);
            var monHoc_LopHoc = lstMH;
            return Json(monHoc_LopHoc, JsonRequestBehavior.AllowGet);

        }

        private List<DanhMucMonHoc> listMonHoc(string userName)
        {
            int idTruong = Cmon.getIdtruong(userName, db);
            string namhoc = Cmon.GetNamHienTai(idTruong);
            
            var lstMH = (from umh in db.Users_Monhoc.Where(t => t.UserName == userName && t.idTruong == idTruong && t.NamHoc == namhoc)
                         join mh in db.ASSIGN_LOP_MonHoc on new { umh.idTruong, umh.MaLop, umh.MaMonHoc } equals new { mh.idTruong,mh.MaLop,mh.MaMonHoc}
                                         select new DanhMucMonHoc
                                         {
                                             MaMon = mh.MaMonHoc.Trim(),
                                             TenMon = mh.TenMonHoc
                                         }
                         ).GroupBy(x => x.MaMon).Select(z => z.OrderBy(i => i.MaMon).FirstOrDefault()).ToList();
            DanhMucMonHoc dmnh = new DanhMucMonHoc();
            dmnh.MaMon = "-1";
            dmnh.TenMon="--Chọn môn học--";
            lstMH.Insert(0, dmnh);
            return lstMH;
        }

        private bool CheckPermission(int idTruong, string namHoc)
        {
            string userName = getUserName();
            //var _userName = (from ul in db.Users_LopHoc
            //                 join um in db.Users_Monhoc on new { ul.idTruong, ul.NamHoc, ul.UserName, ul.MaLop } equals new { um.idTruong, um.NamHoc, um.UserName, um.MaLop }
            //                 where ul.UserName == userName
            //                 select ul).FirstOrDefault();

            // var lh = (from l in db.LopHocs.Where(t => t.idTruong == idTruong && t.NamHoc == namHoc)
            //          join um in db.Users_Monhoc on new { l.MaLop, l.idTruong, l.NamHoc } equals new { um.MaLop, um.idTruong, um.NamHoc }
            //          join ul in db.Users_LopHoc on new { l.MaLop, l.idTruong, l.NamHoc } equals new { ul.MaLop, ul.idTruong, ul.NamHoc }
            //          where ul.UserName == username && um.UserName == username

            var _userName = (from l in db.LopHocs.Where(t => t.idTruong == idTruong && t.NamHoc == namHoc)
                      join um in db.Users_Monhoc on new { l.MaLop, l.idTruong, l.NamHoc } equals new { um.MaLop, um.idTruong, um.NamHoc }
                      join ul in db.Users_LopHoc on new { l.MaLop, l.idTruong, l.NamHoc } equals new { ul.MaLop, ul.idTruong, ul.NamHoc }
                      where ul.UserName == userName && um.UserName == userName
                              select l).FirstOrDefault();


            if (_userName != null && !string.IsNullOrEmpty(_userName.MaLop))
                return true;
            else
                return false;
        }

        

        [HttpGet]
        public ActionResult hienDanhSachNhanXet(int idTruong, int type, int thang, string maMonHoc)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Thongbao");

            }
            string userName = getUserName();

            var dsNhanXet = (from nhanxet in db.DM_NhanXetMau_GVBM
                             where nhanxet.idTruong == idTruong && nhanxet.LoaiNhanXet == type && nhanxet.Thang == thang && nhanxet.MaMonHoc == maMonHoc && nhanxet.UserCreated == userName
                             orderby nhanxet.TenNhanXet
                             select nhanxet).ToList();

            return View(@"~/Views/GiaoVienBoMon/HienThiDanhSachNhanXet.cshtml", dsNhanXet);
        }

        [HttpPost]
        public ActionResult ThemDanhSachThuVienMauCau(string maKhoi, string thangNX, string loaiNX, string maMonHoc, int[] danhSachMau)
        {
            //1. Kieem tra xem noi dung dua vao da co hay chua
            //2. Neu chua co thi thuc hien viec chen moi, neu co roi thi thuc hien cap nhat


            string userName = getUserName();
            int idTruong = Cmon.getIdtruong(userName, db);
            string namHoc = Cmon.GetNamHienTai(idTruong);
            string tenMonHoc = Cmon.GetnameMonhoc(maMonHoc);
            string mess = "";
            try
            {
                for (int i = 0; i < danhSachMau.Length; i++)
                {
                    int id = danhSachMau[i];
                    var thuvienMau = (from thuvien in db.ThuVien_NhanXetMauGVBM
                                      where thuvien.ID == id
                                      select thuvien.Noidung).FirstOrDefault();
                    // lay ra noi dung chen vao bang
                    DM_NhanXetMau_GVBM DMNXGVBM = new DM_NhanXetMau_GVBM();
                    DMNXGVBM.idTruong = idTruong;
                    DMNXGVBM.LoaiNhanXet = (short)Convert.ToInt16(loaiNX);
                    DMNXGVBM.Thang = (short)Convert.ToInt16(thangNX);
                    DMNXGVBM.MaNhanXet = DateTime.Now.Ticks.ToString();
                    DMNXGVBM.MaMonHoc = maMonHoc;                    
                    DMNXGVBM.TenNhanXet = thuvienMau;
                    DMNXGVBM.UserCreated = userName;
                    DMNXGVBM.isDefault = false;
                    db.AddToDM_NhanXetMau_GVBM(DMNXGVBM);
                    db.SaveChanges();
                }
            }

VnEduPlus/Views/GiaoVienBoMon/AddKienThuc.cshtml
@model VnEduPlus.DM_NhanXetMau_GVBM

<form id="formAdd">
  @*  <div style="float:left; width:150px">Mã tiêu chí</div>
    <div style="float:right; width:320px"><input type="text" style="border:1px dashed black; text-align:left;" name="MaKienThuc" id="MaKienThuc" value="" /><a style="color:red">(*)</a></div>
 *@   <div style="float: left; width: 200px; margin-top:5px">Nội dung câu nhận xét</div>
    <div style="float: right; width: 460px; margin-top: 5px">
    <input type="text" style="border:1px dashed black; text-align:left; width: 430px;" name="TenKienThuc" id="TenKienThuc" value="" /><a style="color:red">(*)</a></div>
  @*  <div style="float:left; width:150px; margin-top:5px">Mặc định</div>*@
   @* <div style="float: right; width: 320px; margin-top: 5px">*@
    <input type="checkbox" style="display:none;" name="isDefault" id="isDefault" value="0" />
    @*</div>*@

</form>

VnEduPlus/Views/GiaoVienBoMon/AddNangLuc.cshtml
@model VnEduPlus.DM_NhanXetMau_GVBM

<form id="formAddNL">
  @*  <div style="float:left; width:150px">Mã tiêu chí</div>
    <div style="float:right; width:320px"><input type="text" style="border:1px dashed black; text-align:left;" name="MaNangLuc" id="MaNangLuc" value="" /><a style="color:red">(*)</a></div>
  *@  <div style="float: left; width: 200px; margin-top:5px">Nội dung câu nhận xét</div>
    <div style="float: right; width: 460px; margin-top: 5px">
    <input type="text" style="border:1px dashed black; text-align:left; width: 430px;" name="TenNangLuc" id="TenNangLuc" value="" /><a style="color:red">(*)</a></div>
  @*  <div style="float:left; width:150px; margin-top:5px">Mặc định</div>
    <div style="float: right; width: 320px; margin-top: 5px">
    <input type="checkbox" name="isDefault" id="isDefault" value="0" /></div>
*@

<input type="checkbox" style="display:none;" name="isDefault" id="isDefault" value="0" />
</form>

VnEduPlus/Views/GiaoVienBoMon/AddNhanXet.cshtml
@model VnEduPlus.DM_NhanXetMau_GVBM

<form id="formAdd">
     <div style="float: left; width: 200px; margin-top:5px">Nội dung câu nhận xét</div>
    <div style="float: right; width: 460px; margin-top: 5px">
    <input type="text" style="border:1px dashed black; text-align:left; width: 430px;" name="TenNhanXet" id="TenNhanXet" value="" /><a style="color:red">(*)</a></div>
  
    <input type="checkbox" style="display:none;" name="isDefault" id="isDefault" value="0" />
 

</form>

VnEduPlus/Views/GiaoVienBoMon/AddPhamChat.cshtml
@model VnEduPlus.DM_NhanXetMau_GVBM

<form id="formAddPC">
  @*  <div style="float:left; width:150px">Mã tiêu chí</div>
    <div style="float:right; width:320px"><input type="text" style="border:1px dashed black; text-align:left;" name="MaPhamChat" id="MaPhamChat" value="" /><a style="color:red">(*)</a></div>
*@    <div style="float: left; width: 200px; margin-top:5px">Nội dung câu nhận xét</div>
    <div style="float: right; width: 460px; margin-top: 5px">
    <input type="text" style="border:1px dashed black; text-align:left;width: 430px;" name="TenPhamChat" id="TenPhamChat" value="" /><a style="color:red">(*)</a></div>
 @*   <div style="float:left; width:150px; margin-top:5px">Mặc định</div>
    <div style="float: right; width: 320px; margin-top: 5px"><input type="checkbox" name="isDefault" id="isDefault" value="0" /></div>
  *@  
  <input type="checkbox" style="display:none;" name="isDefault" id="isDefault" value="0" />

</form>

VnEduPlus/Views/GiaoVienBoMon/DanhSachMauNhanXet.cshtml
@model List<VnEduPlus.ThuVien_NhanXetMauGVBM>

<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 <!-- import css bootstrap css and js ( bat buoc phai co)-->
 <link rel="stylesheet" href="@Url.Content("~/css/bootstrap/bootstrap.min.css")">
 <link href="@Url.Content("~/css/jquery.dataTables.css")" rel="stylesheet" type="text/css" />
 <link rel="stylesheet" href="@Url.Content("~/css/common.css")">
 <link href="@Url.Content("~/css/kehoach.css")" rel="stylesheet" type="text/css" />
 <script src="@Url.Content("~/js/bootstrap/js/bootstrap.min.js")"></script>
 <script src="@Url.Content("~/Scripts/jquery.dataTables.min.js")" type="text/javascript"></script>
</head>

<script type="text/javascript">
    //Todo
    $(document).ready(function () {
        $('input[type="checkbox"]').on('change', function () {
            $('input[name="' + this.name + '"]').not(this).prop('checked', false);
        });

        $('#luuthuvien').click(function () {
            var maKhoi = $('#khoinx').val(),
                thangnx = $('#thangnx').val(),
                loaiNX = $('#loainx').val(),
                maMonHoc =$('#maMonHoc').val(),
                arrayCauHoi = [];
            debugger;

            $('.checked').each(function (evt) {
                var checked = $(this).is(":checked");
                if (checked) {
                    arrayCauHoi.push(this.id);
                }
            });

            var thuVienMau = {
             maKhoi: maKhoi,
             thangNX: thangnx,
             loaiNX: loaiNX,
             maMonHoc: maMonHoc,
             danhSachMau: arrayCauHoi
            
            };

            $.ajax({
                type: 'post',
                contentType: 'application/json; charset=utf-8',
                dataType: "json",              
                url: '@Url.Action("ThemDanhSachThuVienMauCau", "GiaoVienBoMon")',
                data: JSON.stringify(thuVienMau),
                success: function (data) {
//                    debugger;
                    if (data != 'ERROR') {
                        alert('Bạn đã lựa chọn câu nhận xét thành công');
                        
                    } else {
                        alert('Dữ liệu bạn thêm vào có vấn đề, liên hệ với quản trị để biết thêm thông tin');
                    }

                    return;
                },

                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to retrieve specification options.')
                }
            });


        });

    });                              //end document
     
</script> 

<div class="ThuVienNhanXetContainerHeader">
   <div> <strong>@ViewBag.tenTruong</strong> - Năm học: @ViewBag.namHoc</div>
   <div class="chonmaucau"><h1> Thư viện mẫu câu</h1> </div>
</div>
<input type="hidden" id="loainx" value="@ViewBag.loaiNX"/>
<input type="hidden" id="thangnx" value="@ViewBag.thang"/>
<input type="hidden" id="khoinx" value="@ViewBag.maKhoi"/>
<input type="hidden" id="maMonHoc" value="@ViewBag.maMonHoc"/>
 <div class="container" id="content">  
    <div class="luuymaucau"><span style="color:Red">Lưu ý: Tại mỗi thời điểm bạn chỉ có thể chọn được một mẫu câu</span></div>
    <div id="danhSachMauNXContainer">
        <table id="danhSachMauNX" class="table table-striped table-bordered" style="table-layout: auto;" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th style="width: 4%;" align="center">STT</th>                             
                    <th style="width: 90%;">Nội dung nhận xét</th>             
                    <th style="width: 6%;" align="center">Chọn</th>
                </tr>
            </thead>
            <tbody>
                @{
                     for (int i = 0; i < Model.Count(); i++)
                     {  
                        string STT = (i+1).ToString();
                        string noiDungNX = Model[i].Noidung;
                         <tr>
                            <td align="center">@STT</td> 
                            <td>@noiDungNX</td>
                            <td align="center"><input type="checkbox" id="@Model[i].ID" class="checked" name="qs" value="@Model[i].ID" /></td>
                        
                        </tr> 
                    }
                }
            </tbody>
        </table>
     </div>
     <div class="footer"><input class="btn btn-primary" type="button" value="Lưu câu thư viện" id="luuthuvien" /></div>
    </div>
 

 

VnEduPlus/Views/GiaoVienBoMon/EditKienThuc.cshtml
@model VnEduPlus.DM_NhanXetMau_GVBM

@{
    if(Model!=null)
    {
        string check="";
        if (Model.isDefault) { check = "checked"; }
        string idtieuchi="id_"+Model.MaNhanXet;
        string tentieuchi = "ten_" + Model.MaNhanXet;
        string isdefault = "isdefault_" + Model.MaNhanXet;
        <form id="formEdit">
         @*   <div style="float:left; width:150px">Mã tiêu chí</div>*@
            <div style="float:right; display:none; width:320px"><input type="text" style="border:1px dashed black; text-align:left;" readonly="readonly" name="MaKienThuc" id="@idtieuchi" value="@Model.MaNhanXet" /><a style="color:red">(*)</a></div>
            <div style="float: left; width: 200px; margin-top:5px">Nội dung câu nhận xét</div>
            <div style="float: right; width: 460px; margin-top: 5px">
            <input type="text" style="border:1px dashed black; text-align:left;width: 430px;" name="TenKienThuc" id="@tentieuchi" value="@Model.TenNhanXet" /><a style="color:red">(*)</a></div>
           @* <div style="float:left; width:150px; margin-top:5px">Mặc định</div>
            <div style="float: right; width: 320px; margin-top: 5px"><input type="checkbox" name="isDefault" id="@isdefault" @check value="0"/></div>*@
            <input type="checkbox" style="display:none;" name="isDefault" id="isDefault" value="0" />
    
        </form>
    }
}

VnEduPlus/Views/GiaoVienBoMon/GiaoVienBoMon.cshtml
@model VnEduPlus.Models.FormKienThuc
@{
    ViewBag.Title = "Mẫu nhận xét GVBM";
}
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<html lang="en">
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 
    <meta charset="utf-8" />
    <title>jQuery UI Autocomplete - Combobox</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/swfobject.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.uploadify-3.1.min.js")" type="text/javascript"></script>
    <link href="@Url.Content("~/Content/uploadify.css")" rel="stylesheet" type="text/css" media="screen"/>
    <link rel="stylesheet" href="@Url.Content("~/css/bootstrap/bootstrap.min.css")">
	<!-- Trung lam -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<link rel="stylesheet" href="@Url.Content("~/menucss/normalize.css")">
	<link rel="stylesheet" href="@Url.Content("~/menucss/stylemenu.css")">
	<link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
    <script src="@Url.Content("~/js/bootstrap/js/bootstrap.min.js")"></script>

    <style type="text/css">
        .transItems
        {
            border: 0;
            background: transparent;
            width:28px;
        }
        .row
        {
            background-color:#eee;
        }
        .altrow
        {
            background-color:#fff;
        }
        
       .selected {
        background:#FECBE0;
         }

        .ui-dialog-titlebar-close {
            background: url("../../css/images/ui-icons_888888_256x240.png") repeat scroll -93px -128px rgba(0, 0, 0, 0);
            border: medium none;
        }

            .ui-dialog-titlebar-close:hover {
                background: url("../../css/images/ui-icons_222222_256x240.png") repeat scroll -93px -128px rgba(0, 0, 0, 0);
            }
    </style>
    
</head>
  
    <script type="text/javascript">
    //Todo
        $(document).ready(function () {

            $('#thang, #danhMucTieuChi, #danhMucMonHoc').change(function () {

                var $thang = $('#thang').val();
                var $danhMucTieuChi = $('#danhMucTieuChi').val();

                if (validator($thang, 'Tháng') && validator($danhMucTieuChi, 'Tiêu chí')) {
                    if ($danhMucTieuChi === '1') {
                        showThuVien($thang,1);
                    } else if ($danhMucTieuChi === '2') {
                        showThuVien($thang,2);
                    } else if ($danhMucTieuChi === '3') {
                        showThuVien($thang,3);
                    }

                }
            });

        });    //end document

        function showThuVien(thang,tieuchi) {
            var idTruong = $('#idtruong').val();
            var namHoc = $('#namhocht').val();
            var mamonhoc = $('#danhMucMonHoc').val();
            $.ajax({
                cache: true,
                type: 'GET',
                url: '@Url.Action("HienThiDanhSach", "GiaoVienBoMon")',
                data: { idTruong: idTruong, namHoc: namHoc, thang: thang, idLoaiNhanXet: tieuchi, mamonhoc: mamonhoc },
                success: function (data) {
                    $("#container").empty();
                    $("#container").html(data);
                },

                error: function (xhr, ajaxOptions, thrownError) {
                    alert('Failed to retrieve specification options.')
                }

            });
        }


        // Validator element
        function validator(value,element) {
          if(value=='-1')
          {
            //alert(element + ' phải có được lựa chọn');
            return false;
          } else return true;
        
        }


    </script>
<body >
<!-- Trung lam -->
        @RenderPage("~/Views/Shared/_MainMenu.cshtml");
       

        <input type="hidden" id="idtruong" name="idtruong" value="@ViewBag.idtruong" />
        <input type="hidden" id="namhocht" name="namhocht" value="@ViewBag.namhientai" />
    
        <table width="100%" style="border: 0px; background: #fff; z-index: 3; position: fixed; left: 0; width: 100%;">
          <tr> <td style="border: 0px; padding: 35px 0px 0px 0px; font-size:16px; font-weight: bolder; text-transform: uppercase" colspan="10" align=center> Mẫu nhận xét môn học</td></tr>
            <tr>
                <td style="border: 0px; padding: 10px 0px;" colspan="10" align=center>
                    <strong>Người đăng nhập: @ViewBag.tenuser  &nbsp;&nbsp;&nbsp;-&nbsp;&nbsp;&nbsp;   Năm học: @ViewBag.namhientai</strong>
                </td>
            </tr>

            <tr>
                <td style="border: 0px;" colspan="30" id="fisrtline">
                    <table width="100%" border="0" style=" background: #fff; text-align: center;">
                        <tr valign="top">
                             <!--
							 <td style="border: 0px; height: 10px; width: 33%; text-align: center;">Khối: @Html.DropDownList("makhoi", "Chọn khối")</td>
							-->
                            <td style="border: 0px; height: 50px;">
                                Chọn môn học:
                                @Html.DropDownListFor(x => Model.danhMucMonHoc,new SelectList(ViewBag.danhMucMonHoc, "MaMon", "TenMon"), new {style="width:160px;"})

                            </td>

                            <td style="border: 0px; height: 50px;">
                                Chọn tiêu chí:
                                @Html.DropDownListFor(x => Model.danhMucTieuChi,new SelectList(ViewBag.danhMucTieuChi, "id", "name"), new {style="width:180px;"})

                            </td>
                           
                            <td style="border: 0px;">
                                Chọn tháng:
                                @Html.DropDownListFor(
                            x => Model.thang,
                                              new SelectList(ViewBag.danhMucThang, "id", "name"), new {style="width:160px;"}
                            )

                            </td>
                            <td style="border: 0px;"></td>
                            <td style="border: 0px;"></td>
                            <td style="border: 0px;"></td>
                            <td style="border: 0px;"></td>
                            <td style="border: 0px;" colspan="11"></td>
                            <td style="border: 0px;" colspan="9">

                                @*<img class="toolbarover" style="float: left" src="@Url.Content("~/Images/icons/save.png")" alt="Lưu lại" id="imgonesave" name="imgone"  onclick="getvalues();">*@
                            </td>
                            <td style="border: 0px;" id="exportExcel">
                                @*<img class="toolbarover" style="float: left" src="@Url.Content("~/Images/icons/xuatexcel.png")" alt="Xuất Excel" id="imgone" name="imgone">*@
                            </td>
                            <!--
                                        <td style="border: 0px;" id="importExcell" >

                                         @using (Html.BeginForm("Import", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                         {
                                            <div>
                            <input type="file" name="fileData" id="fileData" />
                                            <input type="submit" id="upload"  value="upload"/>
                                             </div>
                                         }

                                        </td>
                                          -->
                        </tr>
                    </table>
                </td>
            </tr>

        </table>

        <table style=" width: 100%;">
            <tr>
                <td style="border: 0px" colspan="30" id="container"></td>
            </tr>

        </table>



</body>
</html>